### ISSUE TITLE
几个与word版论文模板不一致的地方

### ISSUE THREAD

**Issue by yangli-xjtu** [obster-y/XJTU-thesis#10]
针对研究生院下载1.2.7版本，以下是几个与word模板不一致之处
1. 还请再核实各级标题、图/表标题的段前段后。以subsection (1.1.1) 为例，word模板段前0.5行，段后0行。
2. 致谢行距设置为了1.5，word模板为1.2。决议行距设置1.5，word模板为20磅。
3. 常规评阅人名单的三列太近了。这个不是问题，只是看起来很奇怪。
4. 独创性声明页=>“研究生\hskip 2cm 所提交”，word模板已经没有“\hskip 2cm ”。

以下不确定，仅供参考：
1. 中文摘要和英文摘要之间无需\cleardoublepage。
2. 页码是正确的，但是bookmark page number与实际页码不匹配。例如英文目录页码为XI，但是bookmark页码已经开始从1计数。这个我还没找到问题所在。

**Comment by yangli-xjtu** [comment]
还有两个建议：为biblatex添加gbpub=false选项，避免不必要的自动信息添加；取消添加\nocite{*}选项，未引用的论文不应加入参考文献。

**Comment by obster-y** [comment]
考虑到部分内容可能已修复过，以下所有的回答均以 dev 分支最新提交为准，同时建议使用 dev 分支的较新提交版本。

不一致之处：
1. 就以从零(\chapter)开始的第 2 级标题(\subsection)，Word 模板中并非段后 0 行，而是段后 8pt。经过对比，目前设置的段前段后有轻微的不一致，但已做调整，同时调整了标题文字与编号的间距
2. Word 模板中很多编号列表并不是真正的编号列表，而是多个以编号开头的段落，它们的行段间距和正文的一致，但实际上它们应该是编号列表。因此如果觉得 LaTeX 的和 Word 不像是正常的，可以自己在 Word 插入编号列表验证一下
3. 已做调整
4. 经查，现在 Word 模板确实去掉了此空白，但是由于我所获得的上一次授予学位的纸质学位论文，此处留出的空白是为了手写研究生姓名，同时考虑到 Word 模板也有自相矛盾的地方，不可照单全收，因此现阶段不准备更新此处，直到与学位办确定清楚后再修改

不确定之处：
1. 根据我可获取的去年的学位论文，中文摘要与英文摘要需要 \cleardoublepage，确保英文摘要从奇数页开始
2. 在 Linux 编译并使用 okular，在 Win10 编译并使用 Foxit，均没有发现所说的 bookmark 页码问题，并附上两张截图。也有可能是我并不明白所说的问题，如不一致，请再详细举例描述
![foxit](https://user-images.githubusercontent.com/55270856/142560867-947fb066-6775-43df-87d1-90492d1b10f9.png)
![okular-r](https://user-images.githubusercontent.com/55270856/142561197-f0cadbc5-086b-4cc5-8e7c-7fb499f9d6d4.png)
3. 已添加 gbpub=false
4. 已取消 \nocite{*}

**Comment by yangli-xjtu** [comment]
经过检查，不确定问题2是由于我自己的bug。感谢~
