### ISSUE TITLE
[BUG] [TeX/Word] 参考文献中中文学位论文格式

### ISSUE THREAD

**Issue by Rainmes** [obster-y/XJTU-thesis#100]
**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：[Win 10 ]
 - TeX 发行版：[TeXLive 2021 ]
 - TeX 编辑器：[TeXStudio 
 - TeX 编译方式：[latexmk ]
 - Word 版本：[2021 / ...]

**Bug 说明**
生成参考文献中中文学位论文格式
张和生．地质力学系统理论[D]．太原理工大学，1998．
word模板中格式
[5]	张和生．地质力学系统理论［D］．太原：太原理工大学，1998．
问题：
1.没有学校所在的地址
2.D前后符号为半角，word模板中为全角（预答辩前指出的问题）

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
非必要不要上传代码截图

**其他说明**

**Comment by sikouhjw** [comment]
> 问题：
> 1.没有学校所在的地址

是你该反思一下，你的 bib 是不是漏写了信息。
```
@phdthesis{zhanghesheng1998dizhilixue,
  author      = {张和生},
  school      = {太原理工大学},
  title       = {地质力学系统理论},
  year        = {1998},
  address     = {太原},
}
```
```tex
\documentclass{ctexart}
\RequirePackage[hyperref=true,backend=biber,defernumbers=true,style=gb7714-2015,gbalign=left,gbpub=false]{biblatex}
\addbibresource[location=local]{xampl-zh.bib}
\begin{document}
\cite{zhanghesheng1998dizhilixue}
\printbibliography
\end{document}
```
![图片](https://user-images.githubusercontent.com/49770925/231130228-52f052ff-05fb-4a59-acf4-45ac60a2af24.png)

**Comment by Rainmes** [comment]
^_^您发给我的信件已经收到^_^
                                             认真的rain.




This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by obster-y** [comment]
对于第二个问题：
1. 如果没有阅读「提问前必读」，请先阅读，如已阅读，这条跳过
2. 这一项目不是为了 100% 复现 word 模板的「样式」，而是要把所有模板中明确注明的要求实现
3. 如果以 word 模板为准，那么 word 模板中的文字要求提到了以国标为准，但 word 模板给出的样例和国标给出的样例不符（可自行搜索已关闭的 issue），这时应该以谁为准？
4. 如果以 word 模板给出的样例为准，回到第二条
5. 如果以国标为准，那么国标首先没有规定使用全角或半角字符，其次国标文件中的具体样例明显是半角字符，因此这里使用半角字符是合理的

也就是说，这一问题首先是不成立的，如果硬要说成立，也不在模板的处理范围，而是应该自行查阅相关宏包的使用手册解决

对于第一个问题，我刚想答来着，但是楼上已经答了，总得来说，因为参考文献样式并非这一模板的专有部分，而是由其他宏包控制的，这一点在 README 中有清晰的说明，因此我怀疑你没有认真阅读说明

**Comment by Rainmes** [comment]
> > 问题：
> > 1.没有学校所在的地址
> 
> 是你该反思一下，你的 bib 是不是漏写了信息。
> 
> ```
> @phdthesis{zhanghesheng1998dizhilixue,
>   author      = {张和生},
>   school      = {太原理工大学},
>   title       = {地质力学系统理论},
>   year        = {1998},
>   address     = {太原},
> }
> ```
> 
> ```
> \documentclass{ctexart}
> \RequirePackage[hyperref=true,backend=biber,defernumbers=true,style=gb7714-2015,gbalign=left,gbpub=false]{biblatex}
> \addbibresource[location=local]{xampl-zh.bib}
> \begin{document}
> \cite{zhanghesheng1998dizhilixue}
> \printbibliography
> \end{document}
> ```
> 
> ![图片](https://user-images.githubusercontent.com/49770925/231130228-52f052ff-05fb-4a59-acf4-45ac60a2af24.png)

抱歉，从谷歌学术直接引用的，没有注意到

**Comment by Rainmes** [comment]
> 对于第二个问题：
> 
> 1. 如果没有阅读「提问前必读」，请先阅读，如已阅读，这条跳过
> 2. 这一项目不是为了 100% 复现 word 模板的「样式」，而是要把所有模板中明确注明的要求实现
> 3. 如果以 word 模板为准，那么 word 模板中的文字要求提到了以国标为准，但 word 模板给出的样例和国标给出的样例不符（可自行搜索已关闭的 issue），这时应该以谁为准？
> 4. 如果以 word 模板给出的样例为准，回到第二条
> 5. 如果以国标为准，那么国标首先没有规定使用全角或半角字符，其次国标文件中的具体样例明显是半角字符，因此这里使用半角字符是合理的
> 
> 也就是说，这一问题首先是不成立的，如果硬要说成立，也不在模板的处理范围，而是应该自行查阅相关宏包的使用手册解决
> 
> 对于第一个问题，我刚想答来着，但是楼上已经答了，总得来说，因为参考文献样式并非这一模板的专有部分，而是由其他宏包控制的，这一点在 README 中有清晰的说明，因此我怀疑你没有认真阅读说明

抱歉，问题已解决
