### ISSUE TITLE
在写博士论文，用pdflatex 编译编译不会出现字符重叠，而用xelatex编译 $ f^{’}$ 会出现字符重叠，怎么办？

### ISSUE THREAD

**Issue by thisnum** [obster-y/XJTU-thesis#11]

**Comment by thisnum** [comment]
![QQ截图20211121151728](https://user-images.githubusercontent.com/39940863/142753439-c146a044-0475-4779-929c-2f66f8af6e2e.png)

**Comment by sikouhjw** [comment]
和 https://github.com/obster-y/XJTU-thesis/issues/7 是同一个问题，用 https://github.com/obster-y/XJTU-thesis/issues/7#issuecomment-966861972 试试

**Comment by thisnum** [comment]
> 和 #7 是同一个问题，用 [#7 (comment)](https://github.com/obster-y/XJTU-thesis/issues/7#issuecomment-966861972) 试试

刚刚看了 #7的问题，并没有找到解决方案， #7是由于加粗斜体出现的字符重叠，我的问题是正常的公式，有字符重叠，在pdflatex中没有重叠问题，使用xelatex编辑就会出现字符重叠问题。

**Comment by sikouhjw** [comment]
> 

1. #7 的本质是字体乱用导致的
2. 你的问题也是这个问题
3. 解决方法为什么你不试一下？

**Comment by thisnum** [comment]
> 不好意思打扰了，初学latex，看了#7 并没有找到解决方法；

![QQ截图20211121155355](https://user-images.githubusercontent.com/39940863/142754255-bd6c43b7-feaa-46ad-bf49-a57c1d27e46c.png)

1、在写论文论文时直接套用的交大latex模板，并未对模板内的内容作出改动，我应该怎么修改？
2、同样在winedt+texlive2021环境下，同样的代码：$ f^{’}$ ，用pdflatex编译没问题，用xelatex编辑编译就会出现字符重叠；

**Comment by sikouhjw** [comment]
1. 作者给的改动 https://github.com/obster-y/XJTU-thesis/commit/8f6cb111f863cc2d9fc097d121e593b5669abde4#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221 是在 https://github.com/obster-y/XJTU-thesis/tree/dev 上改的
2. 你需要 clone dev 分支上的模板
3. 然后把内容移过去／只更换 cls 文件（注意看使用方法有无变化）

**Comment by thisnum** [comment]
> 1. 作者给的改动 [8f6cb11#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221](https://github.com/obster-y/XJTU-thesis/commit/8f6cb111f863cc2d9fc097d121e593b5669abde4#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221) 是在 https://github.com/obster-y/XJTU-thesis/tree/dev 上改的
> 2. 你需要 clone dev 分支上的模板
> 3. 然后把内容移过去／只更换 cls 文件（注意看使用方法有无变化）

感谢大神，问题已解决~
