### ISSUE TITLE
来自打印店的情况反馈

### ISSUE THREAD

**Issue by JinglezZ** [obster-y/XJTU-thesis#12]
作者您好，我近期去打印了论文并送去格式审查，获得了一些格式上的意见，也向您反馈一下
主要是以下两个方面：

1. 目录部分二级、三级标题的缩进和 word 版本有些差异，word 版本的缩进更大一点，这个问题您好像已经在 #10  中提到了；
2. 【摘要】、【致谢】和【攻读学位期间取得的研究成果】三个地方的段落后面似乎都存在段后距，word 版本里面没有段后距。

另外，如果您修改 dev 分支的话，能不能把调整的位置在回复里引用一下，方便我们回去修改本地的设置。非常感谢您！

**Comment by JinglezZ** [comment]
补充：我们学院格式审查的老师的意见，参考文献中缩写字母之间不能存在空格
![image](https://user-images.githubusercontent.com/59874268/144582383-53ec5e80-07d8-456c-a5f1-ab4d95c5df92.png)
虽然与国标不符，但是您能不能设置选项可以选择性保持与 word 版本一致呢？

**Comment by sikouhjw** [comment]
这得请教 @hushidong 了

**Comment by obster-y** [comment]
1. 目录部分确实与 Word 模板不一致，已修改
2. 这三个部分，Word 模板后确实是有 8 磅的段后距离，我检查的是刚从学位办重新下载的版本
3. 我使用 Word 模板中 参考文献一章第一节第三段的例子，作者 Metcalf S W，按照我的理解就是说要以 METCALF SW 的形式显示？似乎 Word 模板中这一节的参考文献第 17 条就是这样做的，但是这已经自己和自己（之第一节第三段）冲突了。在 Word 模板自我矛盾的情况下，我认为使用国标的要求更合理。所以我并不准备修改、也不建议你修改这一点，用 Word 模板自相矛盾的事实，说服学院的格式审查老师接受国标更省时省力。

每次调整的位置请直接在 GitHub 上查看最近的 commit，里面直接有 diff，不需要引用。

**Comment by JinglezZ** [comment]
> 1. 目录部分确实与 Word 模板不一致，已修改
> 2. 这三个部分，Word 模板后确实是有 8 磅的段后距离，我检查的是刚从学位办重新下载的版本
> 3. 我使用 Word 模板中 参考文献一章第一节第三段的例子，作者 Metcalf S W，按照我的理解就是说要以 METCALF SW 的形式显示？似乎 Word 模板中这一节的参考文献第 17 条就是这样做的，但是这已经自己和自己（之第一节第三段）冲突了。在 Word 模板自我矛盾的情况下，我认为使用国标的要求更合理。所以我并不准备修改、也不建议你修改这一点，用 Word 模板自相矛盾的事实，说服学院的格式审查老师接受国标更省时省力。

您好，我参考的 word 模板是研究生院 2020-12-31 发布的模板，网址为：http://gs.xjtu.edu.cn/info/1209/7605.htm
在这个模板中，中文摘要1.2倍行距，无段后距，无空行
![image](https://user-images.githubusercontent.com/59874268/144694187-dd697300-1881-464c-bc1e-1968050c4129.png)
英文摘要1.2倍行距，无段后距，段后空一行
![image](https://user-images.githubusercontent.com/59874268/144694203-23b3eab1-676c-476c-a2fa-82cdc1eb458e.png)
致谢与成果列表部分和摘要处的要求一致。
请问是我下载的 word 模板版本不对吗，是不是还有最新版本的 word 模板？如果是的话麻烦您贴个链接，万分感谢！

最后，参考文献部分的内容，我尝试去说服一下我们院格式审查的老师。

**Comment by obster-y** [comment]
经过检查，是我的 Word 的 Normal.dotm 文件出了点问题，默认的正文样式具有 8pt 的段后，刚再其他机器打开发现没有，现在已修正

**Comment by JinglezZ** [comment]
> 经过检查，是我的 Word 的 Normal.dotm 文件出了点问题，默认的正文样式具有 8pt 的段后，刚再其他机器打开发现没有，现在已修正

您好，您这个修复好像只修复了致谢中段后距的问题，摘要中仍然存在段后距。
另外注意到您在之前的某次提交中，把 `\linespread{1.33}` 修改为了 `\linespread{1.2}`，是减少了基本的行距吗？
我目前仍然保留了  `\linespread{1.33}`  ，并且将 `\setlength{\parskip}{8pt}`  调整为 `\setlength{\parskip}{0pt}`，但是摘要中仍然存在段后距。
非常感谢您！

**Comment by JinglezZ** [comment]
> > 经过检查，是我的 Word 的 Normal.dotm 文件出了点问题，默认的正文样式具有 8pt 的段后，刚再其他机器打开发现没有，现在已修正
> 
> 您好，您这个修复好像只修复了致谢中段后距的问题，摘要中仍然存在段后距。 另外注意到您在之前的某次提交中，把 `\linespread{1.33}` 修改为了 `\linespread{1.2}`，是减少了基本的行距吗？ 我目前仍然保留了 `\linespread{1.33}` ，并且将 `\setlength{\parskip}{8pt}` 调整为 `\setlength{\parskip}{0pt}`，但是摘要中仍然存在段后距。 非常感谢您！

补充，将`\setlength{\parskip}{8pt}`调整为`\setlength{\parskip}{0pt}`后，目录之间的段后距也变很窄了

**Comment by yangli-xjtu** [comment]
> > 经过检查，是我的 Word 的 Normal.dotm 文件出了点问题，默认的正文样式具有 8pt 的段后，刚再其他机器打开发现没有，现在已修正
> 
> 您好，您这个修复好像只修复了致谢中段后距的问题，摘要中仍然存在段后距。 另外注意到您在之前的某次提交中，把 `\linespread{1.33}` 修改为了 `\linespread{1.2}`，是减少了基本的行距吗？ 我目前仍然保留了 `\linespread{1.33}` ，并且将 `\setlength{\parskip}{8pt}` 调整为 `\setlength{\parskip}{0pt}`，但是摘要中仍然存在段后距。 非常感谢您！

word模板正文是1.2倍行距，office word 2013及之后单倍行距是字号1.08倍[https://zh.wikipedia.org/wiki/%E8%A1%8C%E8%B7%9D](url)，1.2倍行距则是1.2*1.08=1.296。配置文件中\fontsize设置了字号1.0倍行距，所以\linespread应该设置为{1.296}。作者很久没回复，我不太清楚1.33和1.2的设置原因，以上仅供参考

**Comment by obster-y** [comment]
当时提这个 issue 的时候有事，回来又忙忘了也忘了打 label，现在修了。
