### ISSUE TITLE
[BUG] 请填写简短的Package biblatex Warning: Biber reported the following issues with 'agrawal2019mnl': - Datamodel: Entry 'agrawal2019mnl' (References/reference.bib): Invalid field 'lansortorder' for entrytype 'article'. Bug 说明

### ISSUE THREAD

**Issue by zhb-xjtu** [obster-y/XJTU-thesis#120]
- [ ] 我已阅读过[提问前必读](https://github.com/obster-y/XJTU-thesis/issues/35) (意思是如果没读就去读，读后请改括号内内容为 x)

**软件信息（请补全，请务必填写准确）**
 - 操作系统：[Win 10 / Win 7 / MacOS / Linux发行版 / ...]
 - TeX 发行版：[TeXLive 202X / MikTeX / CTeX / ...]
 - TeX 编辑器：[TeXStudio / WinEdt / VS Code / ...]
 - 模板编译方式：[latexmk / xelatex+biber / pdflatex / ...]

**Bug 说明**
为了实现 XX 功能/效果
使用了 XX 语句/命令
得到了 XX 结果

**最小代码示例**
如果可以，请在附件上传最小代码示例(minimal working example, MWE)，以及日志 / 辅助文件

**错误截图**
非必要不要上传代码截图

**其他说明**
其他值得提到的内容

**Comment by sikouhjw** [comment]
请你详细描述你的问题，而不是只修改标题。

**Comment by obster-y** [comment]
看字，重发，还这样提问直接屏蔽
