### ISSUE TITLE
[BUG] 公式内容对上一行行距不一致

### ISSUE THREAD

**Issue by walru0** [obster-y/XJTU-thesis#123]
- [√] 我已阅读过[提问前必读](https://github.com/obster-y/XJTU-thesis/issues/35) (x)

**软件信息（请补全，请务必填写准确）**
 - 操作系统：[Win 11]
 - TeX 发行版：[TeXLive 202X ]
 - TeX 编辑器：[VS Code]
 - 模板编译方式：[Vscode中自带的fast(xe)]

**Bug 说明**
公式内容对上一行行距不一致，会根据上一行内容的长度调整行距。
如果上一行内容在长度较长，则会增大行距，反之则正常。

感觉是latex为了防止公式内容与上一行的内容覆盖，自动进行调整的。但是这样调整后格式就很怪，前后间距不统一。而且模板已经设置过上下间距半行了就不需要再自动调整了。有没有什么办法可以设置关掉这个自动调整？

![说明](https://github.com/obster-y/XJTU-thesis/assets/96094527/2ebe671b-bf18-4857-aea0-54d1698e90f9)

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/discussions/34

**Comment by walru0** [comment]
> [sikouhjw/gdutthesis#34](https://github.com/sikouhjw/gdutthesis/discussions/34)

感谢回复，我使用链接中的方法设置了全局间距，将不包含分式的简单公式的行距统一了。但是对于高度较高的复杂公式，与正文的间距又不太合适。
为了调整复杂公式与正文的间距，我将\vspace{}放到公式之前可以手动调整公式与前一行正文的行距，但是在公式后使用的时候却不起作用。
比如对于以下内容：
公式
正文1
正文2

在公式和正文1之间使用\vspace{}的时候，只会调整正文1和正文2之间的间距。
请问有没有什么方法可以调整公式到内容1之间的间距？即使只能针对每个公式单独进行手动调整也行。

**Comment by walru0** [comment]
> > [sikouhjw/gdutthesis#34](https://github.com/sikouhjw/gdutthesis/discussions/34)
> 
> 感谢回复，我使用链接中的方法设置了全局间距，将不包含分式的简单公式的行距统一了。但是对于高度较高的复杂公式，与正文的间距又不太合适。 为了调整复杂公式与正文的间距，我将\vspace{}放到公式之前可以手动调整公式与前一行正文的行距，但是在公式后使用的时候却不起作用。 比如对于以下内容： 公式 正文1 正文2
> 
> 在公式和正文1之间使用\vspace{}的时候，只会调整正文1和正文2之间的间距。 请问有没有什么方法可以调整公式到内容1之间的间距？即使只能针对每个公式单独进行手动调整也行。

我发现把连接中的设置放到单独的equation里面去就可以了

**Comment by sikouhjw** [comment]
我在链接里说了：
1. 一般情况使用 `align`，`align` 不合适时，用 `equation`
2. 可以试试这个间距
```tex
\ctex_after_end_preamble:n
  {
    \setlength{\abovedisplayskip}{0.5\baselineskip - 0.5\ccwd + 3pt}
    \setlength{\belowdisplayskip}{8pt}
    \setlength{\abovedisplayshortskip}{0pt}
    \setlength{\belowdisplayshortskip}{0.5\baselineskip - 0.5\ccwd}
  }
```
