### ISSUE TITLE
在章节内放图的时候代码报错

### ISSUE THREAD

**Issue by jixinyuan1996** [obster-y/XJTU-thesis#124]
- [x] 我已阅读过[提问前必读](https://github.com/obster-y/XJTU-thesis/issues/35) (意思是如果没读就去读，读后请改括号内内容为 x)

**软件信息（请补全，请务必填写准确）**
 - 操作系统：[MacOS]
 - TeX 发行版：[MacTex]
 - TeX 编辑器：[pycharm]
 - 模板编译方式：[latexmk]

**Bug 说明**
我在论文里放Figure的时候出现了提示错误的波浪线，主要就是这句 我的图片也有放置在相应位置 

\includegraphics[width=1\textwidth]{Figures/2_intro_excample.pdf}

**最小代码示例**
begin{figure}[H]
\centering
\subfigure[Label noise distribution on client $p$ and $q$. Black are correct labels and Red are noisy labels. ]{
\begin{minipage}{11.2cm}
\centering
% \includegraphics[width = 0.71 \textwidth]{figure/figure_Loss_distribution/_Loss.pdf}
\includegraphics[width=1\textwidth]{Figures/2_intro_excample.pdf}
\label{intro_excample}
\end{minipage}
}
\subfigure[CL with noisy labels \& FL with heterogeneous noisy labels.]{
\begin{minipage}{6.1cm}
\centering
 \includegraphics[width=1\textwidth]{Figures/2_FedAVG_noisy_label.png}
\label{intro_comparation}
\end{minipage}
}
\caption{(a): The heterogeneous label noise distributions encompass diverse true class samples or varying label noise transitions. (b): The performance comparison between CL and FL on CIFAR-10 with the rate of label noise 0.2, 0.5, and 0.8.}
\label{fig:figure1}
% \vspace{-4mm}
\end{figure}

![error1](https://github.com/obster-y/XJTU-thesis/assets/35824739/06bbb402-b433-4edb-828e-05319a3a2dcd)

**其他说明**
其他值得提到的内容

**Comment by vinodthale** [comment]
Hi, I have already written my Ph.D. thesis using another XJTU latex template. Last week in June, I was just waiting for the final defense. If possible, I can share my code with you. I tried XJTU-Latex code in this repository, but so far, no success. Did you face any compilation issues?

**Comment by obster-y** [comment]
不清楚你是否解决了，我只能说我没见过这种用法，建议如果想要插入子图请参考此处示例 https://github.com/obster-y/XJTU-thesis/blob/c92bb01721af8477df23ada3a3a0dce57f1b0947/Main_Spine/c2.tex#L69-L83
