### ISSUE TITLE
关于数学环境的括号显示问题

### ISSUE THREAD

**Issue by EleLawrence** [obster-y/XJTU-thesis#13]
作者您好！

在使用您最新的dev#12模板之后，由于Times字体引起的数学字体粘连问题（特别是上下角标）已经得到了非常好的解决。但是，我发现矩阵的方括号[]，以及方程组所使用的大括号{}，等等，都会显得非常粗，比较影响美观。我尝试了多种编译方式，也换了PDF阅读器，但这个问题始终存在，所以我认为可能是数学字体导致的问题。

这该如何解决呢？

最后，非常感谢您的模板，帮助很大！

**Comment by sikouhjw** [comment]
1. 西文衬线体是 tnr，那么数学字体也应该是同样的风格的，这里用的是 `XITS Math`
2. 『好看与否』是主观感受，字体作者认为好看就是好看，你不喜欢可以不用
3. 你可以更换数学字体，后果自负

**Comment by EleLawrence** [comment]
> 

非常感谢您的回复！既然它确实就是这个样子的，那就没问题了；因为我这边括号之类显示得比较粗，以为是格式上存在问题。

再次感谢！
