### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by pacer123J** [obster-y/XJTU-thesis#14]
我在运行学位论文模板时无法生成参考文献，请问这个问题如何解决，非常感谢

**Comment by sikouhjw** [comment]
1. 查看文档
2. 查看 issue
3. 命令行编译
4. 你为什么什么都没说？

**Comment by pacer123J** [comment]
您好，我在使用模板时始终无法生成参考文献部分，想咨询下怎么解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obster-y/XJTU-thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obster-y/XJTU-thesis] sos (Issue #14)





  
查看文档
 
查看 issue
 
命令行编译
 
你为什么什么都没说？
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pacer123J** [comment]
您好，我没有改动模板关于参考文献的代码，但是自始至终都无法生成参考文献

**Comment by sikouhjw** [comment]
> 您好，我在使用模板时始终无法生成参考文献部分，想咨询下怎么解决
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "obster-y/XJTU-thesis" ***@***.***&gt;; 发送时间:&nbsp;2021年12月13日(星期一) 上午9:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [obster-y/XJTU-thesis] sos (Issue #14) 查看文档 查看 issue 命令行编译 你为什么什么都没说？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

毫无意义的提问，请阅读我上面说的东西再来提问。

**Comment by pacer123J** [comment]
> 1. 查看文档
> 
>     2. 查看 issue
> 
>     3. 命令行编译
> 
>     4. 你为什么什么都没说？

不好意思，我没有get到您的意思

**Comment by sikouhjw** [comment]
> > 1. 查看文档
> >    
> >    2. 查看 issue
> >    3. 命令行编译
> >    4. 你为什么什么都没说？
> 
> 不好意思，我没有get到您的意思

你要用 `biber` 编译，那你编译了吗？你用什么编辑器？配置对了吗？
文档查看了吗？

**Comment by pacer123J** [comment]
怎样使用biber，我使用的是texworks的xelatex编译，您提到的文档是哪个文档，非常感谢您的回复

**Comment by sikouhjw** [comment]
1. 文档是这个模板的手册
2. 请你查看选择 `xelatex` 的地方有没有 `biber`
3. 请你学会命令行编译，命令行输入 `texdoc install-LaTeX`

**Comment by pacer123J** [comment]
谢谢您的回复，选择 xelatex 的地方有biber，我在main.tex中最下方加了您提到的texdoc install-LaTeX，然后再编译就出现了参考文献，不知您说的命令行编译是否是这个意思

**Comment by sikouhjw** [comment]
不是这个意思，请上网搜『命令行』。

**Comment by pacer123J** [comment]
谢谢您的回复

**Comment by pacer123J** [comment]
另外还有个小问题，就是论文中的表格如果要加表注，用什么命令会比较好，谢谢

**Comment by sikouhjw** [comment]
你是不是需要 `\caption`？请读书 `texdoc lshort-zh`。

**Comment by pacer123J** [comment]
谢谢您的回复，不是，是表格下方的注释，不是表格的名字




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月13日(星期一) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obster-y/XJTU-thesis] sos (Issue #14)





 
你是不是需要 \caption？请读书 texdoc lshort-zh。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
请自行检索，https://www.jianshu.com/p/110714b2a535

**Comment by pacer123J** [comment]
好的，谢谢
