### ISSUE TITLE
博士学位论文模板里原有的摘要如何去除

### ISSUE THREAD

**Issue by pacer123J** [obster-y/XJTU-thesis#16]
添加了新的摘要后，原摘要内容还在，如何清除原来的？答辩委员会会议决议也有这个问题。希望您能帮忙解答下，非常感谢

**Comment by sikouhjw** [comment]
什么叫新的摘要？什么叫原摘要？给能复现的代码。

**Comment by pacer123J** [comment]
刚刚找到解决办法了，非常感谢您的回复

**Comment by sikouhjw** [comment]
> 刚刚找到解决办法了，非常感谢您的回复

1. 怎么解决的？可以补充在回答里
2. 解决了可以关闭 issue

**Comment by JinglezZ** [comment]
> > 刚刚找到解决办法了，非常感谢您的回复
> 
> 1. 怎么解决的？可以补充在回答里
> 2. 解决了可以关闭 issue

我猜他说的是 `\lipsum`
