### ISSUE TITLE
模板誊写（已解决）

### ISSUE THREAD

**Issue by liugang1234567** [obster-y/XJTU-thesis#17]

**Comment by sikouhjw** [comment]
> 参考文献处处是bug，这模板中很多语句直接引的样例文献。

什么 bug？

> 只是使用的时候真心不方便。

哪里不方便？

> 文章样例的引用很乱，删除替换超级麻烦，偶尔有点不注意，就出bug。

举具体的例子？

> 一定要XeLaTeX编译器替换成Latexmk吗？直接在2018原XeLaTeX模板上改不香吗~

1. `latexmk` 只是帮你调用了 `bibtex`/`biber`，没有禁止你使用 `xelatex`
2. 什么叫“2018原XeLaTeX模板”？作者重写说明之前的模板都不够好。

**Comment by JinglezZ** [comment]
我200页篇幅的论文花了整整四天时间转过来了，参见 #8 。我觉得如果都是从零开始写论文的话，肯定是这个模板好用，语法和说明文档都更规范，你说的那些问题我也基本上没遇到。。。
另外，作者近期都是有别的事情吗，好久没来处理 issue 了。

**Comment by sikouhjw** [comment]
> 另外，作者近期都是有别的事情吗，好久没来处理 issue 了。

他最近有事没时间处理

**Comment by liugang1234567** [comment]
可能我在2018版写好后，原以为直接copy过来，修改一下关键部分即可。结果发现不是这样，确实需要重新梳理。 我再重新誊一下吧，从零开始写论文的话，应该是这个模板好用。

此外，有个需求：咱们写文章肯定是使用latex模板方便些，但是导师审阅往往需要word版本（word审阅方便）。我在网上试了好几种latex转word的方法，如Pandoc、TeX2Word等，都没有转化成功（可能毕业论文比较长导致内存不够或其他缘故）。 用pdf转化的word会有很多小问题。

请问有没有其他好的方案呢？

**Comment by JinglezZ** [comment]
> 可能我在2018版写好后，原以为直接copy过来，修改一下关键部分即可。结果发现不是这样，确实需要重新梳理。 我再重新誊一下吧，从零开始写论文的话，应该是这个模板好用。
> 
> 此外，有个需求：咱们写文章肯定是使用latex模板方便些，但是导师审阅往往需要word版本（word审阅方便）。我在网上试了好几种latex转word的方法，如Pandoc、TeX2Word等，都没有转化成功（可能毕业论文比较长导致内存不够或其他缘故）。 用pdf转化的word会有很多小问题。
> 
> 请问有没有其他好的方案呢？

应该是没有很好的方案，除非你老板也会用 latex 。我的做法是把摘要、结论之类的单独整理成一个 word 文档，连同 pdf 一起发过去，因为我老板看学位论文只着重改这两个地方。大部分老板应该都没空帮学生改全文吧。

**Comment by sikouhjw** [comment]
> 可能我在2018版写好后，原以为直接copy过来，修改一下关键部分即可。结果发现不是这样，确实需要重新梳理。 我再重新誊一下吧，从零开始写论文的话，应该是这个模板好用。

就我的经验来看，只要之前写的够规范，搬到另一个模板是很快的。

> 此外，有个需求：咱们写文章肯定是使用latex模板方便些，但是导师审阅往往需要word版本（word审阅方便）。我在网上试了好几种latex转word的方法，如Pandoc、TeX2Word等，都没有转化成功（可能毕业论文比较长导致内存不够或其他缘故）。 用pdf转化的word会有很多小问题。
> 
> 请问有没有其他好的方案呢？

这是伪需求。
1. 用 LaTeX 模板的前提是：你和你导师有过沟通，协商过后续的审阅、投稿、查重、报告怎么弄
2. 可以给导师 Overleaf 链接，教他用 `changes` 宏包的语法，然后用 `changes` 宏包修改，既简单又方便
3. 本质上这跟 LaTeX 没关系，是一个 pdf -> docx 的问题，以我的经验，用 word 打开 pdf 是最优解，当然给导师纸质稿最省事

**Comment by liugang1234567** [comment]
>
您这三条回复是在说：

1. 让导师去学latex，在导师不主动去学latex的情况下，不用latex模板~
2. 让导师用word打开pdf审阅（尽管导师觉得使用docx格式方便）~

这两条都比较难操作，那先这样吧~ 我去继续誊论文了

**Comment by sikouhjw** [comment]
> > 
> 
> 您这三条回复是在说：
> 
>     1. 让导师去学latex，在导师不主动去学latex的情况下，不用latex模板~
> 
>     2. 让导师用word打开pdf审阅（尽管导师觉得使用docx格式方便）~
> 
> 
> 这两条都比较难操作，那先这样吧~ 我去继续誊论文了

1. 导师可以不学 LaTeX，只要会打字就能用我说的 `changes` 方法
2. 用 word 打开 pdf，然后自己整理好再给导师发过去，辛苦的是自己，毕竟是自己决定用的 LaTeX

**Comment by liugang1234567** [comment]
我刚刚搜了一下有教程，有愿意学的导师可以见以下链接：

https://www.jianshu.com/p/e1efb81a7069

教程《The changes-package》
链接: https://pan.baidu.com/s/1gliO7oozn4che7rMqvCedA 密码: sc2g

**Comment by sikouhjw** [comment]
> 我刚刚搜了一下有教程，有愿意学的导师可以见以下链接：
> 
> https://www.jianshu.com/p/e1efb81a7069
> 
> 教程《The changes-package》 链接: https://pan.baidu.com/s/1gliO7oozn4che7rMqvCedA 密码: sc2g

搜用户手册请用 `texdoc` 或者 ctan，[changes](https://www.ctan.org/pkg/changes)

**Comment by obster-y** [comment]
因为原来的模板使用起来并不方便，所以重做了这个，至于迁移版本，确实不是很容易，但是个人觉得用正则替换一下会比较快
