### ISSUE TITLE
本地编译问题

### ISSUE THREAD

**Issue by jacky123465** [obster-y/XJTU-thesis#18]
> Overleaf 的没有更新，以前的一些小 bug 还存在，之后会更新，个人还是建议本地编译

请问本地编译，出现这三个错误，该如何处理诶。
![image](https://user-images.githubusercontent.com/32159528/148752148-c5d648d0-34e7-4ede-a514-aa63f2018569.png)

_Originally posted by @WujiangXu in https://github.com/obster-y/XJTU-thesis/issues/15#issuecomment-1008739340_

**Comment by sikouhjw** [comment]
1. 发行版是什么？
2. 本地编译的模板怎么下载的？
3. 请使用命令行编译

**Comment by jacky123465** [comment]
您好，我用的texlive2019，使用texstudio编译和命令行编译是同样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 晚上7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obster-y/XJTU-thesis] 本地编译问题 (Issue #18)





  
发行版是什么？
 
本地编译的模板怎么下载的？
 
请使用命令行编译
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
请尽量使用 texlive 2021 编译

**Comment by jacky123465** [comment]
好的，谢谢您啦。我是西安交通大学的余凡，微信号15527382349，如果您有空的话能加下您吗。如果麻烦的话就算了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 晚上7:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obster-y/XJTU-thesis] 本地编译问题 (Issue #18)





 
请尽量使用 texlive 2021 编译
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
具体原因见 https://github.com/obster-y/XJTU-thesis/pull/19。
建议：
1. 用 Overleaf
2. 用 texlive 2021
