### ISSUE TITLE
参考文献角标问题

### ISSUE THREAD

**Issue by decota0910** [obster-y/XJTU-thesis#2]
![6dbffbbc07648612b398dd6fe70c831](https://user-images.githubusercontent.com/60957513/138435275-7c9e380b-0512-4fe0-81c4-030da534306f.png)这是我编译的时候出现的问题，这里使用的是模板tex文件，无改动，本来应该是右上角数字上标，但是出现的是citationkey，并不是数字。
![a74d2fe67806aa14df25959f6b78349](https://user-images.githubusercontent.com/60957513/138435415-edab39d6-0a8c-4044-82f5-3b399b90476a.png)这是本来应该出现的数字。
（我使用的是博士tex文件，问题都是这个参考文献不显示角标）

**Comment by decota0910** [comment]
biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜
| |
decota
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年10月25日 ***@***.***> 写道：

Closed #2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
> 
> biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜 | | decota | | ***@***.*** | 签名由网易邮箱大师定制 在2021年10月25日 ***@***.***> 写道： Closed #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

请您使用命令行编译，编译报什么错呢？

**Comment by obster-y** [comment]
> biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜 | | decota | | ***@***.*** | 签名由网易邮箱大师定制 在2021年10月25日 ***@***.***> 写道： Closed #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

「别的bib文件就可以编译」是指「现在的bib不能编译」的话，建议提供：
1. 编译的具体方式：latexmk 或 命令行手动编译
2. 不能编译的 .bib 文件

**Comment by decota0910** [comment]
你好~我的编译方式是xelatex-biber-xelatex-xelatex这样的顺序。。然后其他的bib使用biber时显示成功，这个是出现错误。附件是我的bib文件~biber提示错误如图所示：


| |
decota
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年11月4日 ***@***.***> 写道：

biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜 | | decota | | @.*** | 签名由网易邮箱大师定制 在2021年10月25日 @.***> 写道： Closed #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

请您使用命令行编译，编译报什么错呢？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
> 
> 你好~我的编译方式是xelatex-biber-xelatex-xelatex这样的顺序。。然后其他的bib使用biber时显示成功，这个是出现错误。附件是我的bib文件~biber提示错误如图所示： | | decota | | ***@***.*** | 签名由网易邮箱大师定制 在2021年11月4日 ***@***.***> 写道： biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜 | | decota | | @.*** | 签名由网易邮箱大师定制 在2021年10月25日 @.***> 写道： Closed #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 请您使用命令行编译，编译报什么错呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

1. 要命令行编译的结果
2. 没有附件
3. 没有图
4. 请不要用邮件回复

**Comment by obster-y** [comment]
> 你好~我的编译方式是xelatex-biber-xelatex-xelatex这样的顺序。。然后其他的bib使用biber时显示成功，这个是出现错误。附件是我的bib文件~biber提示错误如图所示： | | decota | | ***@***.*** | 签名由网易邮箱大师定制 在2021年11月4日 ***@***.***> 写道： biber无法编译问题，谢谢大佬啦。删掉了temp文件也还是不行，但是别的bib文件就可以编译，格式也没有错误，实在是不知道该怎么解决了，毕业在即，打扰了呜呜呜 | | decota | | @.*** | 签名由网易邮箱大师定制 在2021年10月25日 @.***> 写道： Closed #2. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 请您使用命令行编译，编译报什么错呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

首先，在使用说明中说了使用 xe->xe->biber->xe 的顺序，你使用的顺序就不对。

其次，确实没有看到你的图以及附件。

最后，为什么不试试 latexmk 呢，设置 IDE 或命令行手动都可。
