### ISSUE TITLE
为何参考文献在正文引用时都显示数字，没有作者和年份呢？

### ISSUE THREAD

**Issue by thisnum** [obster-y/XJTU-thesis#21]
![QQ截图20220127220549](https://user-images.githubusercontent.com/39940863/151374660-e152e753-6f06-4eb8-a98c-cb6b8e37592a.jpg)

使用的\parencite{}命令，用latexmk main 运行，正文引用文献显示数字[1]，怎么才能显示为 "zhu, et al. (2020)"这种形式呢？

**Comment by sikouhjw** [comment]
![图片](https://user-images.githubusercontent.com/49770925/151376173-92f27172-31a0-4f29-abf2-0c6b1c13e85b.png)
硬是不看使用手册？

**Comment by thisnum** [comment]
把这个下载下来了，是需要修改main.tex 内的参数吗；我在\usepackage{threeparttable}下面添加了包\usepackage{gbt7714}；
运行latexmk main 还是不行

**Comment by sikouhjw** [comment]
1. 模板加载了 `biblatex-gb7714-2015`，使用者不需要再加载同类型的宏包
2. `\usepackage{threeparttable}` 没有被模板加载
3. 请阅读 `texdoc biblatex-gb7714-2015` 宏包手册，上面很清楚的写了如何使用
4. 你需要修改的是
   https://github.com/obster-y/XJTU-thesis/blob/e66afea1c668e9f1ddf1f78a505faed81cd3556c/XJTU-thesis.cls#L1367

**Comment by liugang1234567** [comment]
您好，latex模板中参考文献处生成的作者名均大写了，而word模板中不是均大写的，这个可以修改吗？

**Comment by obster-y** [comment]
> 您好，latex模板中参考文献处生成的作者名均大写了，而word模板中不是均大写的，这个可以修改吗？

https://github.com/obster-y/XJTU-thesis/issues/6

**Comment by thisnum** [comment]
谢谢
