### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by jacky123465** [obster-y/XJTU-thesis#22]
您好，参考文献后期会出现突出来的情况（比其他行长）。与word版本似乎有所区别。请问一下这是怎么回事呢

**Comment by sikouhjw** [comment]
连图都不给？给代码。

**Comment by jacky123465** [comment]
![image](https://user-images.githubusercontent.com/22407341/154898474-4883e533-8197-4204-8bc8-3e3732690c60.png)
您好，就是这一块凸出来的

**Comment by jacky123465** [comment]
![image](https://user-images.githubusercontent.com/22407341/154898591-3139cde9-e8d0-4582-98ba-58ab60bce818.png)
您好，就是这一块凸出来的

**Comment by sikouhjw** [comment]
看起来是没有断行点，可以在 bib 对应的位置加上 `\-` 允许他断行。
```tex
Neuroco\-mputing
```

**Comment by jacky123465** [comment]
> 看起来是没有断行点，可以在 bib 对应的位置加上 `\-` 允许他断行。
> 
> ```
> Neuroco\-mputing
> ```

试了一下您的方法和网上说得加\url方法好像都不行

**Comment by sikouhjw** [comment]
给 bib 的代码

**Comment by obster-y** [comment]
提供一下这一条记录的 .bib 源码以便复现

**Comment by jacky123465** [comment]
> 提供一下这一条记录的 .bib 源码以便复现
`@article{DBLP:journals/ijon/LiuZW20,
	title={Adaptive multi-teacher multi-level knowledge distillation},
	author={Liu, Yuang and Zhang, Wei and Wang, Jun},
	journal={Neurocomputing},
	volume={415},
	pages={106--113},
	year={2020},
	publisher={Elsevier}
}`

**Comment by obster-y** [comment]
> > 提供一下这一条记录的 .bib 源码以便复现
> > `@article{DBLP:journals/ijon/LiuZW20, 	title={Adaptive multi-teacher multi-level knowledge distillation}, 	author={Liu, Yuang and Zhang, Wei and Wang, Jun}, 	journal={Neurocomputing}, 	volume={415}, 	pages={106--113}, 	year={2020}, 	publisher={Elsevier} }`
![20220221_14481645426133_2789x307](https://user-images.githubusercontent.com/55270856/154903336-d610d69a-4229-4728-8c77-002a64f87b1b.png)


刚测试，没有问题，请确保使用的是 dev 分支的最新版本

**Comment by sikouhjw** [comment]
```
@article{DBLP:journals/ijon/LiuZW20,
	title		=	{Adaptive multi-teacher multi-level knowledge distillation},
	author		=	{Liu, Yuang and Zhang, Wei and Wang, Jun},
	journal		=	{Neuroco\-mputing},
	volume		=	{415},
	pages		=	{106--113},
	year		=	{2020},
	publisher	=	{Elsevier}
}
```
怎么会不行呢？你是不是没有删除辅助文件还是没有 `biber`？
![图片](https://user-images.githubusercontent.com/49770925/154903414-470507dc-b65d-4be5-9fee-090dc34e360b.png)

**Comment by obster-y** [comment]
我觉得是没有清除辅助文件

**Comment by jacky123465** [comment]
> 我觉得是没有清除辅助文件

您好，确实是没有清楚辅助文件的问题。万分感谢

**Comment by obster-y** [comment]
> > 我觉得是没有清除辅助文件
> 
> 您好，确实是没有清楚辅助文件的问题。万分感谢

之后提问还请描述清楚问题，提供最小工作示例或部分源码，这样都节省大家时间

**Comment by jacky123465** [comment]
> > > 我觉得是没有清除辅助文件
> > 
> > 
> > 您好，确实是没有清楚辅助文件的问题。万分感谢
> 
> 之后提问还请描述清楚问题，提供最小工作示例或部分源码，这样都节省大家时间

好的好的。多谢啦

**Comment by liugang1234567** [comment]
您好，请问参考文献会议文献中[S.l. : s.n.]怎么去除呢？

**Comment by obster-y** [comment]
> 您好，请问参考文献会议文献中[S.l. : s.n.]怎么去除呢？

请检查您的 XJTU-thesis.cls 中，调用 `biblatex` 宏包时是否启用了 `gbpub=false` 选项，如果没有，请更新至最新的 XJTU-thesis.cls。如果有，请提供 .bib 项。

https://github.com/obster-y/XJTU-thesis/blob/5d81ffda896a4578b8ea686b35d87b0f28fb763b/LaTeX_Template/XJTU-thesis.cls#L1425

**Comment by liugang1234567** [comment]
> > 你好，请参考文献会议文献中[Sl : sn]怎么去除呢？
> 
> 请您的 XJTU-thesis.cls 中，调用`biblatex`宏包时是否启用了`gbpub=false`选项，如果没有，请更新至最新的 XJTU-thesis.cls。如果有，请提供 .bib 项。
> 
> https://github.com/obster-y/XJTU-thesis/blob/5d81ffda896a4578b8ea686b35d87b0f28fb763b/LaTeX_Template/XJTU-thesis.cls#L1425

XJTU-thesis.cls换成最新的https://github.com/obster-y/XJTU-thesis/blob/5d81ffda896a4578b8ea686b35d87b0f28fb763b/LaTeX_Template/XJTU-thesis.cls#L1425 后，
运行后出现新问题：行 91: Emergency stop. \RequireXeTeX

我直接下载模板运行，同样也是报：行 91: Emergency stop. \RequireXeTeX

**Comment by sikouhjw** [comment]
> XJTU-thesis.cls换成最新的
> 
> https://github.com/obster-y/XJTU-thesis/blob/5d81ffda896a4578b8ea686b35d87b0f28fb763b/LaTeX_Template/XJTU-thesis.cls#L1425
> 后，
> 运行后出现新问题：行 91: Emergency stop. \RequireXeTeX
> 
> 我直接下载模板运行，同样也是报：行 91: Emergency stop. \RequireXeTeX

请使用 `xelatex` 编译。

**Comment by liugang1234567** [comment]
> > XJTU-thesis.cls换成最新的
> > https://github.com/obster-y/XJTU-thesis/blob/5d81ffda896a4578b8ea686b35d87b0f28fb763b/LaTeX_Template/XJTU-thesis.cls#L1425
> > 
> > 之后，
> > 运行后出现新问题：行91：紧急停止。\需要XeTeX
> > 我直接下载模板运行，同样也是报：行 91：紧急停止。\需要XeTeX
> 
> 请使用`xelatex`编译。

我使用xelatex对模板进行了编译，可正常执行，只是编译后生成的pdf中不显示参考文献

**Comment by liugang1234567** [comment]
![image](https://user-images.githubusercontent.com/32161314/158945473-2e8d291c-5671-462f-93d6-ac6511d02557.png)
![image](https://user-images.githubusercontent.com/32161314/158945632-e3145221-02ba-4f8c-8a50-60fc817b9027.png)

最新latex模板和word模板的一级标题和内容间的间距是不是不一样呢？

**Comment by obster-y** [comment]
是不一样，但是没有必要扣这么细，因为不是在做 Word 的复刻。

另外，有疑问请先搜索历史issue，然后有必要的话，去开新的 issue，不要在一个已经 close 的 issue 下反复提和标题无关的问题。

最后，如果想调可以自己去改源码。

**Comment by zhanghaok** [comment]
> 我觉得是没有清除辅助文件

你好，你说的清楚辅助文件，辅助文件是什么呢，怎么清除
