### ISSUE TITLE
“答辩委员会会议决议”页页眉错误

### ISSUE THREAD

**Issue by JinglezZ** [obster-y/XJTU-thesis#24]
Latex模板中页眉为“答辩委员会会议决议”：
![image](https://user-images.githubusercontent.com/59874268/155309488-4018a102-bb89-47fb-8a85-9d56ac369dd9.png)
而 Word 模板中页眉为“答辩委员会决议”：
![image](https://user-images.githubusercontent.com/59874268/155309592-b5252f62-1604-4eea-be40-77c5d7e37287.png)

**Comment by sikouhjw** [comment]
![图片](https://user-images.githubusercontent.com/49770925/155449345-c29059e6-fd92-498f-9552-41727e555b63.png)
从代码上看，不应该出现问题，请双击页眉刷新域代码。

**Comment by JinglezZ** [comment]
> ![图片](https://user-images.githubusercontent.com/49770925/155449345-c29059e6-fd92-498f-9552-41727e555b63.png) 从代码上看，不应该出现问题，请双击页眉刷新域代码。

这个问题是我昨天在学位论文印制点打印的时候那里的老师指出的。按照学位办的要求，Word中页眉的形式是正确的，所以应该修改 latex 模板，使其和 Word 模板保持一致

**Comment by sikouhjw** [comment]
1. 你要说清楚 Word 模板从哪来的，信息要给全
2. 一般情况，页眉都要与 chapter 保持一致，这很明显是你说的『Word 模板』有问题
3. 可以用下面的代码实现你的需求，在导言区加上
    ```tex
    \makeatletter
    \fancypagestyle{test}{
        \fancyhf{}
        \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\display@header}
        \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont 答辩委员会决议}
        \fancyfoot[LE,RO]{\fontsize{9pt}{10.8pt}\selectfont\Roman{page}}
    }
    \makeatother
    ```
    在 `Main_Miscellaneous/decision.tex` 第二行加上 `\thispagestyle{test}`

**Comment by JinglezZ** [comment]
> 1. 你要说清楚 Word 模板从哪来的，信息要给全
> 2. 一般情况，页眉都要与 chapter 保持一致，这很明显是你说的『Word 模板』有问题
> 3. 可以用下面的代码实现你的需求，在导言区加上
>    ```
>    \makeatletter
>    \fancypagestyle{test}{
>        \fancyhf{}
>        \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\display@header}
>        \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont 答辩委员会决议}
>        \fancyfoot[LE,RO]{\fontsize{9pt}{10.8pt}\selectfont\Roman{page}}
>    }
>    \makeatother
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    在 `Main_Miscellaneous/decision.tex` 第二行加上 `\thispagestyle{test}`

学位论文模板来自研究生院发布的版本[http://gs.xjtu.edu.cn/info/1209/7605.htm](url)，其中页眉和标题是不一致的。
通常情况下两者是要保持一致，但是昨天得到的反馈是，学位办的老师特意提醒学位论文印制处的老师，让他们在帮学生打印论文的时候检查这个位置的页眉，要按照 Word 模板中的设置来执行，也就是页眉内容为“答辩委员会决议”，章节标题和目录为“答辩委员会会议决议”。

**Comment by sikouhjw** [comment]
LaTeX 的解决方案是按上面说的做，本项目的 Word 模板[^1]要改起来就只能多加两个分节符了，真麻烦。

[^1]: https://github.com/obster-y/XJTU-thesis/tree/dev/Word_Template

**Comment by obster-y** [comment]
从没想过还有这种事情，当初设计这个模板的真是鬼才，等下修好了发

**Comment by JinglezZ** [comment]
谢谢两位，我也是想不到学位论文的模板能有这么多坑和扯皮。。
