### ISSUE TITLE
本地编译后显示与使用手册不一致

### ISSUE THREAD

**Issue by llan-ml** [obster-y/XJTU-thesis#25]
tex版本：
```
TeX 3.141592653 (TeX Live 2021/W32TeX)
kpathsea version 6.3.3
```
下载`dev`分支后，本地编译默认的tex文件，可以编译成功，但是生成的pdf和附带的”使用手册.pdf“在外观上不一致。

本地编译的pdf：
![image](https://user-images.githubusercontent.com/22030149/155570758-771b992b-097d-4c95-84be-806419b03203.png)
使用手册.pdf：
![image](https://user-images.githubusercontent.com/22030149/155570892-ddb8acf2-58cc-4deb-b63f-2ea4ffa938d4.png)

差异主要在（1）行间距、段间距等各种间距；（2）本地编译的pdf中字体看着更虚、更浅。

麻烦帮忙看一下这个问题，谢谢！

**Comment by obster-y** [comment]
是的，
（1）是因为使用手册为二进制文件，不想经常用 git 更新，因此使用手册不完全与最新发布的格式一致。在 e8f5cd61bb24f5575f16b7866fb156193899df42 中修改了各项间距以保持与官方 Word 版本适配。
（2）是因为不同平台的字体设置原因，主要是 Fandol 和 SimSun 之间的区别，但是并不影响实际使用，之前也未见打印时遇到这个问题。
https://github.com/obster-y/XJTU-thesis/blob/0bfabd550368f6f25ae9722ce3e5c62575049ae4/LaTeX_Template/XJTU-thesis.cls#L256-L286

**Comment by llan-ml** [comment]
@obster-y 您好，这些间距是不是改的太小了？
我看Word_Template里面的间距也是比较大的：
![image](https://user-images.githubusercontent.com/22030149/155641773-9cf52cf1-c3dc-40e4-ab2d-40659c62494e.png)
但是Latex编译出来的间距看着很小，并且看着也不太美观：
![image](https://user-images.githubusercontent.com/22030149/155641997-7aa4590f-0774-4ca8-9584-2fba5d951f3c.png)

我贴的Word_Template就是dev分支中自带的word模板，您对照的官方Word版本的链接方便给一下吗？

**Comment by sikouhjw** [comment]
如果对字体有疑惑，可以用 `pdffonts` 来检测字体。
```
pdffonts main.pdf
```

**Comment by sikouhjw** [comment]
> @obster-y 您好，这些间距是不是改的太小了？

LaTeX 模板与 Word 模板『行距』是基本一致的，你觉得 Word 模板间距大是因为标题、正文设置了段前段后，这与 LaTeX 的设置对不上，所以你才会觉得有问题。

至于应该怎么做，得看官方的文件了。不过由于学位办认可 LaTeX 模板，我认为不需要太纠结这些格式问题，并且毕业生用这份模板也没有被审核出有问题。

**Comment by sikouhjw** [comment]
额，我看完《提交论文流程》[^1]和《西安交通大学硕士、博士学位论文模板-2021版》[^2]发现，这基本就是仓库里的模板，我觉得还是别纠结好了。

[^1]: http://www.lib.xjtu.edu.cn/info/1102/1217.htm
[^2]: http://gs.xjtu.edu.cn/info/1209/7605.htm

**Comment by llan-ml** [comment]
http://gs.xjtu.edu.cn/info/1209/7605.htm 该链接中Latex模板v1.2.7在间距上和word模板的视觉效果是差不多的，但是目前dev分支上的视觉效果差别很大~

**Comment by llan-ml** [comment]
> LaTeX 模板与 Word 模板『行距』是基本一致的，你觉得 Word 模板间距大是因为标题、正文设置了段前段后，这与 LaTeX 的设置对不上，所以你才会觉得有问题。

段前段后是和`\parskip`对应吗？

**Comment by sikouhjw** [comment]
> > LaTeX 模板与 Word 模板『行距』是基本一致的，你觉得 Word 模板间距大是因为标题、正文设置了段前段后，这与 LaTeX 的设置对不上，所以你才会觉得有问题。
> 
> 段前段后是和`\parskip`对应吗？

段后是 `\parskip`。我建议别纠结，出问题再说。

**Comment by llan-ml** [comment]
先改用master上的模板了，dev分支上的外观差距太大了~~~

**Comment by obster-y** [comment]
由于一些原因，我在制作1.2.7的时候看到的word模板是有段后 8pt 的间距的，但是在 #12 中经过提醒，发现实际并没有段后 8pt 间距，所以去掉了。同时之前没调好标题的前后间距，现在更新好了，建议切换到dev下最新版
