### ISSUE TITLE
请问如果使用latex书写的论文，查重怎么处理呢？

### ISSUE THREAD

**Issue by WujiangXu** [obster-y/XJTU-thesis#26]
latex只能生成pdf文档出来，到后面查重的时候，会不会出现问题呢？

**Comment by obster-y** [comment]
这个问题完全不必担心，因为起码大的查重系统都是支持 pdf 检测的。

**Comment by sikouhjw** [comment]
1. pdf 是可查重的
2. 如果学院在某个阶段要求**必须**上交一份 Word 文件，那就不要用 LaTeX
