### ISSUE TITLE
Mac 下编译出错

### ISSUE THREAD

**Issue by majx1997** [obster-y/XJTU-thesis#28]
![image](https://user-images.githubusercontent.com/38154161/155992824-fdb1f077-0027-4ff1-bccd-1ec6db0de60e.png)
您好，我在mac系统下编译您贡献的模板一字未改的情况下出现了上述问题，网上没有找到有用的答案，请问您知道大概是什么原因引起的吗？

**Comment by sikouhjw** [comment]
用命令行编译 `xelatex --shell-escape main.tex`，在 https://github.com/obster-y/XJTU-thesis#%E5%9F%BA%E6%9C%AC%E7%8E%AF%E5%A2%83 写了

**Comment by majx1997** [comment]
感谢您的回复，mac 下必须用命令行进行编译，可以这样理解吗？我在mac下 用vscode 编译也是出现大量bug。

**Comment by sikouhjw** [comment]
> 感谢您的回复，mac 下必须用命令行进行编译，可以这样理解吗？我在mac下 用vscode 编译也是出现大量bug。

1. 不可以
2. 我给命令行的意思是，命令行是最本质的编译方式
3. 编辑器不重要，命令行才重要
4. 编辑器报错是因为配置有问题
5. 可以将 `--shell-escape` 放到配置里，具体去看官方的文档

**Comment by majx1997** [comment]
好的，很感谢您的回复。

**Comment by majx1997** [comment]
<img width="755" alt="image" src="https://user-images.githubusercontent.com/38154161/155997912-1592f2fb-3933-4892-8181-5496a79c5da0.png">
抱歉再次打扰您，我使用xelatex --shell-escape main.tex编译仍然会出现类似问题，能否麻烦您再看一下。

**Comment by sikouhjw** [comment]
我大概知道问题从哪来了
1. https://github.com/obster-y/XJTU-thesis/blob/e66afea1c668e9f1ddf1f78a505faed81cd3556c/XJTU-thesis.cls#L247
   模板引入了 `ctex` 宏包，`ctex` 宏包自定义了 `\heiti` 等命令
2. https://github.com/obster-y/XJTU-thesis/blob/e66afea1c668e9f1ddf1f78a505faed81cd3556c/XJTU-thesis.cls#L269-L275
   这部分代码又多定义了一些命令，所以把 `\heiti` 和 `\songti` 那两行注释应该就可以了

这是 bug，之前没遇到可能是没人用 mac？

**Comment by majx1997** [comment]
按照您的指点已经不报错了，非常感谢您。
我顺便也把vscode添加配置放上来，也许会减少一些mac用户的麻烦，哈哈。
![image](https://user-images.githubusercontent.com/38154161/155999865-36781070-1d52-451a-b7b6-26659dbbc3e6.png)
