### ISSUE TITLE
关于数学公式行间距以及显示的疑问

### ISSUE THREAD

**Issue by PrinceVictor** [obster-y/XJTU-thesis#29]
作者您好，我有几个疑问，想请教一下作者。
1.我从研究生院word模板上查看了公式的行间距段前段后都是0行，但是在您的dev分支上查看word模板的时候说明的是段前段后0.5行，
想请问以哪个为准啊？
2.我分别用您提供的word模板（左）和latex模板（右）编写同样数学公式进行测试，感觉latex模板的字体更粗一点更像黑体，以及间距更大一些

![image](https://user-images.githubusercontent.com/30308024/156615232-f3c73c72-8a83-4af2-b3be-26452cec948d.png)

**Comment by sikouhjw** [comment]
第二个问题：word 和 LaTeX 本就不能一模一样。

word 用的像是 mathtype，times 风的字体，LaTeX 用的是 XITS Math。

反正应该都能过审，保持一致也做不到，不用太纠结。

**Comment by obster-y** [comment]
第一个问题，我不清楚你是在哪里看到段前段后是0行的，模板第一章绪论1.1第一段，明确说明了间隔0.5行，公式(1-1)选中段落也是前后0.5行的间距。
第二个问题，可以自己选择调整字体，直接改 .cls，虽然并不推荐。

**Comment by PrinceVictor** [comment]
> 

您好，关于段前段后的0.5行我已经注意到了，之前是我没注意到，但是即使段前段后间隔0.5行，使用latex模板下的公式间距还是比较明显大于word下面间隔0.5行的距离

**Comment by sikouhjw** [comment]
> > 
> 
> 您好，关于段前段后的0.5行我已经注意到了，之前是我没注意到，但是即使段前段后间隔0.5行，使用latex模板下的公式间距还是比较明显大于word下面间隔0.5行的距离

参考《正文与数学公式之间的间距小怎么办？》[^1]，建议别纠结，学位办都承认

[^1]: https://github.com/sikouhjw/gdutthesis/issues/12

**Comment by PrinceVictor** [comment]
好的，实在麻烦啦，感谢耐心解答

**Comment by llan-ml** [comment]
@PrinceVictor 可以加一个 \setmathfont{Cambria Math}，就和word一样了

**Comment by sikouhjw** [comment]
> @PrinceVictor 可以加一个 \setmathfont{Cambria Math}，就和word一样了

1. Word 用的数学字体是什么？不是固定的
2. mathtype、AxMath 还是原生自带？
3. 最后的结论就是不要纠结，纠结是没有好处的

**Comment by llan-ml** [comment]
只是说有需要的同学可以自己在Preamble区调整一下公式字体，对我而言，模板用的XITS Math字体默认的`\symcal`太花了，所以需要换一下。
