### ISSUE TITLE
参考文献中的作者姓名

### ISSUE THREAD

**Issue by GardenChan** [obster-y/XJTU-thesis#30]
![image](https://user-images.githubusercontent.com/52736709/156734074-0847a782-5637-44a7-ba77-73a37903083d.png)
模板中参考文献的作者姓名都是大写？这个不对吧？需要怎么修改？

**Comment by sikouhjw** [comment]
1. 为什么不对？请给出学校层面的依据
2. 国标就是全大写的

**Comment by GardenChan** [comment]
这是谷歌学术导出来的
![image](https://user-images.githubusercontent.com/52736709/156735462-50e79211-41e4-4cc0-88ca-c44143a85480.png)
这是学校word的模板
![image](https://user-images.githubusercontent.com/52736709/156735542-a75dad12-bc28-4e98-b2af-7a2a818e35c3.png)

**Comment by sikouhjw** [comment]
1. 谷歌学术不代表它是对的，国标就是全大写
2. 本模板也是学位办承认的，请不要纠结
3. 如果你想修改，`texdoc gbt7714`

**Comment by obster-y** [comment]
请先看 #6

**Comment by GardenChan** [comment]
> 
多谢多谢
