### ISSUE TITLE
使用latexmk main.tex命令编译后，段首的空格消失如何处理？

### ISSUE THREAD

**Issue by GardenChan** [obster-y/XJTU-thesis#32]
使用latexmk main.tex命令编译后，段首的空格消失如何处理？
![image](https://user-images.githubusercontent.com/52736709/156975732-13397be5-0cd6-4bc3-ac7a-cc9c7e8542fa.png)

**Comment by sikouhjw** [comment]
没报错吗？哪个版本的模板？发行版是什么？

**Comment by GardenChan** [comment]
看了一下日志是报错了，1.2.7，tex live 2021

**Comment by sikouhjw** [comment]
> 看了一下日志是报错了，1.2.7，tex live 2021

用命令行编译报什么错呢？

**Comment by GardenChan** [comment]
![image](https://user-images.githubusercontent.com/52736709/156982298-d16ae112-850b-4a9f-9aa1-c6798a14b225.png)
麻烦帮忙看一下

**Comment by sikouhjw** [comment]
建议你把全部文件压缩上传，如果你理解不了命令行编译的意思的话

**Comment by GardenChan** [comment]
我仔细看了一下errors，报错的都是的写列表的地方。就是如下这样的写法
\begin{enumerate}
\item
\item 
\end{enumerate}
我把这些列表都去掉之后，编译就对了，段首的空格也有了，请教一下这是什么问题？人麻了

**Comment by GardenChan** [comment]
您好能加下微信帮我看一下吗 微信号chen_jia_ding

**Comment by GardenChan** [comment]
您好，能麻烦加个微信帮我看一下吗 微信号chen_jia_ding

**Comment by obster-y** [comment]
建议使用 dev 分支最新提交的代码，和 1.2.7 相比更新了很多
