### ISSUE TITLE
关于专硕模版封面与研院提供的word模版不一致的问题

### ISSUE THREAD

**Issue by pandashere** [obster-y/XJTU-thesis#36]
感谢作者的辛苦劳动！
使用中发现了一个问题，研院下载的word模版中，专硕没有“学科名称”一栏，而是“类别（领域）”，但XJTU-thesis提供的专硕word模版封面则是“学科名称”，而latex模版中使用的也是“学科名称”，以下分别是研院提供的封面和thesis提供的封面（都是专硕）
<img width="296" alt="研院模版" src="https://user-images.githubusercontent.com/33127380/159004903-4953e051-1405-442b-8347-d4f953b4acf5.png">
<img width="270" alt="thesis提供模版" src="https://user-images.githubusercontent.com/33127380/159005145-48b3ddb6-34d0-4e34-828b-044c868d2e54.png">
从thesis提供的word模版中可以看到修改日期晚于研院提供的word模版，这是否是图书馆后续修改过的word模版呢？
但研院提供的还是21年1月的word模版，因此我自己将cls文件里这一项硬编码为自己的信息，不知道作者是否可以添加这一选择分支，
方便专硕同学使用呢

**Comment by sikouhjw** [comment]
模板并没有区分学硕专硕，建议在文档类选项区分，这样就容易解决本问题了。

**Comment by pandashere** [comment]
> 模板并没有区分学硕专硕，建议在文档类选项区分，这样就容易解决本问题了。

其实模版里有学硕专硕的选项……但是我看了cls文件里并没有写相关的分支，感觉可能是忘记写了hhhhh

**Comment by obster-y** [comment]
确实，之前没发现这个错误也是很奇怪，已修复
