### ISSUE TITLE
master分支和dev分支用哪一个？

### ISSUE THREAD

**Issue by kamiLight** [obster-y/XJTU-thesis#37]
master分支和dev分支要用哪一个？这两个的段间距、标题与正文的间距、图片和正文的间距感觉差的有点多。

**Comment by sikouhjw** [comment]
根据《提问前必读》[^1]可知
> 请优先使用 latexmk 编译 dev 分支的最新版本，如果使用 v1.2.7，可以通过替换 XJTU-thesis.cls 较为轻松的转换至最新提交

[^1]: https://github.com/obster-y/XJTU-thesis/issues/35

**Comment by kamiLight** [comment]
> 根据《提问前必读》[1](#user-content-fn-1-02b076f796d2987c52021eb48d996a2f)可知
> 
> > 请优先使用 latexmk 编译 dev 分支的最新版本，如果使用 v1.2.7，可以通过替换 XJTU-thesis.cls 较为轻松的转换至最新提交
> 
> ## Footnotes
> 1. [提问前必读 #35](https://github.com/obster-y/XJTU-thesis/issues/35) [↩](#user-content-fnref-1-02b076f796d2987c52021eb48d996a2f)

好的，看到了👌

**Comment by ymzang** [comment]
感谢，在直接使用新的`XJTU-thesis.cls`的情况下，问题已解决。
