### ISSUE TITLE
表格内文字向左紧凑排列问题

### ISSUE THREAD

**Issue by thisnum** [obster-y/XJTU-thesis#38]
![QQ截图20220320231237](https://user-images.githubusercontent.com/39940863/159169281-44e8f702-7b47-4577-bb85-32581d541501.jpg)
![QQ截图20220320231225](https://user-images.githubusercontent.com/39940863/159169285-213521a9-549d-42ac-a003-6032db74a034.jpg)
同样是使用手册代码，粘贴到论文中运行，表格的问题出现了靠左紧凑排列的问题，怎么解决呢？

**Comment by obster-y** [comment]
抱歉，这个问题看起来不是由模板导致的，因为刚在不同环境均编译了模板，没有出现这种情况。

很大可能是你加载了其他宏包或其他控制语句造成的。

建议你逐步注释/取消注释源码，如先只编译这一章，再缩小到这一节这样的流程，并最终提供可以复现错误的源码。

**Comment by thisnum** [comment]
已解决，谢谢~
