### ISSUE TITLE
你好，麻烦请问用这个模板无法编译参考文献

### ISSUE THREAD

**Issue by zhonghua66** [obster-y/XJTU-thesis#4]
#2   [这是我在tex文件里的引用，以及生成的pdf，在最终生成的版本中没有参考文献列表，
![image](https://user-images.githubusercontent.com/93647710/140290959-7ba8dc9c-b725-43ce-aeed-e7ef43d6fbfc.png)
![image](https://user-images.githubusercontent.com/93647710/140290994-b080dcfb-f605-4274-b9e5-13ddf0565eee.png)

P.S用的是biber和Xelatex编译方法，

**Comment by sikouhjw** [comment]
无效提问

**Comment by sikouhjw** [comment]
1. 你给的截图没有任何信息
2. 下载 https://github.com/obster-y/XJTU-thesis/archive/refs/heads/master.zip
3. 在工作目录中，打开命令行输入 `latexmk main` 编译
4. 是否编译成功？
5. 不成功请上传 log 文件

**Comment by obster-y** [comment]
> #2 [这是我在tex文件里的引用，以及生成的pdf，在最终生成的版本中没有参考文献列表， ![image](https://user-images.githubusercontent.com/93647710/140290959-7ba8dc9c-b725-43ce-aeed-e7ef43d6fbfc.png) ![image](https://user-images.githubusercontent.com/93647710/140290994-b080dcfb-f605-4274-b9e5-13ddf0565eee.png)
> 
> P.S用的是biber和Xelatex编译方法，

请注意这里的提示：
https://github.com/obster-y/XJTU-thesis#%E6%89%8B%E5%8A%A8%E7%BC%96%E8%AF%91

这种情况大概率是没有使用 biber 编译文件导致的，如果是手动编译（采用 xe->xe->biber->xe）导致的，请确保这四步都成功进行。如果是使用 IDE (如 TeXStudio)，请查看 Message 栏，看是否进行过 biber 的编译

最后，推荐使用模板自带的 latexmk 脚本编译，在 IDE 里可以设置，或者用命令行手动 latexmk

**Comment by zhonghua66** [comment]
[并没有成功
[main.log](https://github.com/obster-y/XJTU-thesis/files/7474118/main.log)
谢谢你，麻烦了

**Comment by sikouhjw** [comment]
> 
> 
> [并没有成功 [main.log](https://github.com/obster-y/XJTU-thesis/files/7474118/main.log) 谢谢你，麻烦了

```tex
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                main
(biblatex)                and rerun LaTeX afterwards.
```
您没有 `biber`，都说了用命令行编译。

**Comment by zhonghua66** [comment]
![d730b56b5710ca7f0edf89dbf3aceea](https://user-images.githubusercontent.com/93647710/140299585-f55c25b8-9335-46d1-8b20-8925de6cb64f.png)
用Latexmk编译之后是这样的
然后biber编译也会报错
![fa539a8d8c773e14796b10c84b22a2c](https://user-images.githubusercontent.com/93647710/140299810-a0385f1d-f69a-4b88-988e-76c379ca177f.png)
：

**Comment by sikouhjw** [comment]
> 
> 
> ![d730b56b5710ca7f0edf89dbf3aceea](https://user-images.githubusercontent.com/93647710/140299585-f55c25b8-9335-46d1-8b20-8925de6cb64f.png) 用Latexmk编译之后是这样的 然后biber编译也会报错 ![fa539a8d8c773e14796b10c84b22a2c](https://user-images.githubusercontent.com/93647710/140299810-a0385f1d-f69a-4b88-988e-76c379ca177f.png) ：

1. 用命令行编译
2. 要 log 文件
3. 尝试 `latexmk -C main` 删除所有辅助文件，再用『管理员模式』打开命令行，`latexmk main`

**Comment by zhonghua66** [comment]
不好意思，刚刚才理解你说的命令行编译，试过了还是不行，这是log文件，麻烦了
[main.log](https://github.com/obster-y/XJTU-thesis/files/7474589/main.log)

**Comment by sikouhjw** [comment]
> 
> 
> 不好意思，刚刚才理解你说的命令行编译，试过了还是不行，这是log文件，麻烦了 [main.log](https://github.com/obster-y/XJTU-thesis/files/7474589/main.log)

你这仍然不是 `latexmk`，你只用了 `xelatex`

**Comment by thisnum** [comment]
代码：其求解难度会随着问题规模的增大呈现指数形式的增加\cite{li2021effective}。
结果如下图：
![QQ截图20211122114031](https://user-images.githubusercontent.com/39940863/142797538-57a52685-81b7-435a-aae3-3d7c42610645.png)

和你遇到的情况一样，您解决了吗？
我是通过xeLatex-->xeLatex-->BibTex编译,然后就出现了如下错误提示：
![QQ截图20211122114206](https://user-images.githubusercontent.com/39940863/142797658-6921fba2-d9d3-4d6d-a2eb-fc2c13285c0c.png)

**Comment by sikouhjw** [comment]
> 代码：其求解难度会随着问题规模的增大呈现指数形式的增加\cite{li2021effective}。 直接用xeLatex编译 结果如下图： ![QQ截图20211122114031](https://user-images.githubusercontent.com/39940863/142797538-57a52685-81b7-435a-aae3-3d7c42610645.png)
> 
> 和你遇到的情况一样，您解决了吗？
> 
> 如果通过xeLatex-->xeLatex-->BibTex编译,然后就出现了如下错误提示： ![QQ截图20211122114206](https://user-images.githubusercontent.com/39940863/142797658-6921fba2-d9d3-4d6d-a2eb-fc2c13285c0c.png)

您但凡好好的看完上面的讨论都不会有这个问题。

**Comment by obster-y** [comment]
[这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。

[这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。

**Comment by thisnum** [comment]
> [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> 
> [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。

按照上述说明，在命令行输入了 latexmk main回车，
结果显示如下：
![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)

**Comment by sikouhjw** [comment]
> > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
> > 以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
> > 套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。
> 
> 按照上述说明，在命令行输入了 latexmk main回车， 结果显示如下： ![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)

您所谓的『命令行』，不会没有切换到工作目录吧？

**Comment by thisnum** [comment]
> > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
> > > 以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
> > > 套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。
> > 
> > 
> > 按照上述说明，在命令行输入了 latexmk main回车， 结果显示如下： ![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)
> 
> 您所谓的『命令行』，不会没有切换到工作目录吧？
![微信截图_20211124214522](https://user-images.githubusercontent.com/39940863/143249898-41717524-2eb0-412e-a5bd-9f6ef2c74561.png)
直接在winedt下面的命令输入窗口，输入了latexmk main回车；

**Comment by thisnum** [comment]
> > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
> > > > 以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
> > > > 套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。
> > > 
> > > 
> > > 按照上述说明，在命令行输入了 latexmk main回车， 结果显示如下： ![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)
> > 
> > 
> > 您所谓的『命令行』，不会没有切换到工作目录吧？
> > ![微信截图_20211124214522](https://user-images.githubusercontent.com/39940863/143249898-41717524-2eb0-412e-a5bd-9f6ef2c74561.png)
> > 直接在winedt下面的命令输入窗口，输入了latexmk main回车；

应该怎么操作呢？

**Comment by sikouhjw** [comment]
> > > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> > > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
> > > > > 以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
> > > > > 套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。
> > > > 
> > > > 
> > > > 按照上述说明，在命令行输入了 latexmk main回车， 结果显示如下： ![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)
> > > 
> > > 
> > > 您所谓的『命令行』，不会没有切换到工作目录吧？
> > > ![微信截图_20211124214522](https://user-images.githubusercontent.com/39940863/143249898-41717524-2eb0-412e-a5bd-9f6ef2c74561.png)
> > > 直接在winedt下面的命令输入窗口，输入了latexmk main回车；
> 
> 应该怎么操作呢？

打开工作目录下的命令行。

**Comment by thisnum** [comment]
> 

![微信截图_20211124221103](https://user-images.githubusercontent.com/39940863/143254043-e20de7cc-737f-44da-b670-93e42850c041.png)
可以打开默认就是这个工作目录，怎么更改呢？

**Comment by thisnum** [comment]
> > > > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)说了，请没有丰富使用经验者使用 latexmk 编译，丰富使用经验者至少应该会认真阅读文档和错误提示。
> > > > > > [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E6%96%87%E6%A1%A3%E7%BC%96%E8%AF%91) 和 [这里](https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE) 给出了使用的具体编译方式。
> > > > > > 以前没用过latexmk，都是PdfLatex->PdfLatex->BibTex->PdfLatex,生成的pdf，文献都显示正常。
> > > > > > 套用了交大latex模板以后，要求用XeLatex才能编译，直接用XeLatex以后，文献显示就会出现和第一个提问者一样的问题。
> > > > > 
> > > > > 
> > > > > 按照上述说明，在命令行输入了 latexmk main回车， 结果显示如下： ![微信截图_20211124213711](https://user-images.githubusercontent.com/39940863/143248654-901fe3a4-bb23-4d4f-a377-a9ad38b629dd.png)
> > > > 
> > > > 
> > > > 您所谓的『命令行』，不会没有切换到工作目录吧？
> > > > ![微信截图_20211124214522](https://user-images.githubusercontent.com/39940863/143249898-41717524-2eb0-412e-a5bd-9f6ef2c74561.png)
> > > > 直接在winedt下面的命令输入窗口，输入了latexmk main回车；
> > 
> > 
> > 应该怎么操作呢？
> 
> 打开工作目录下的命令行。

搞定了，非常感谢
