### ISSUE TITLE
dev模板vscode编译失败，公式字体偏粗，不生成参考文献

### ISSUE THREAD

**Issue by weihuangsheng** [obster-y/XJTU-thesis#42]
![image](https://user-images.githubusercontent.com/82591388/159403611-d8d69789-ce15-4707-82c6-c6a52500dc01.png)

dev模板下载下来，直接在VSCODE里使用LaTeXmk编译失败，但是在texstudio中编译成功，原因未知。

**Comment by weihuangsheng** [comment]
按照提问前必读的建议，我将.cls文件直接复制到正式发行版中，然而出现了公式字体偏粗的新问题。
![image](https://user-images.githubusercontent.com/82591388/159404471-6be5b851-4deb-4141-a250-868b722ef65b.png)

**Comment by weihuangsheng** [comment]
此外大写字母间距过大
![image](https://user-images.githubusercontent.com/82591388/159404532-77c659ea-9987-4b01-a86b-1db79a806862.png)

**Comment by weihuangsheng** [comment]
最后，仅更新.cls文件后，参考文献没有生成
![image](https://user-images.githubusercontent.com/82591388/159404595-b36c527b-9657-4584-b978-a623546143ea.png)

**Comment by weihuangsheng** [comment]
当然，如果使用texstudio直接编译dev模板，自然是没问题的。
最后，感谢作者的辛苦付出。

**Comment by obster-y** [comment]
1. vscode 编译不成功，而 texstudio 编译成功，很有可能是 vscode 中 latexworkshop 的 tools 的配置问题，这很明显与模板无关，因此请不要自行添加 bug 的标签。

如果使用的是模板提供的 latexworkshop 的配置，请使用 `latexmk_rconly` 项，或自行查询如何配置 latexworkshop 的 tools，确保编译时使用的 Latexmk 参数没有 `-pdf`
https://github.com/obster-y/XJTU-thesis/blob/81b468c3675760eef76f0b64a02e4b021d145112/LaTeX_Template/Materials/Tools/configuration_for_vscode.json#L9-L31

2. 公式偏粗是由于公式字体更换带来的，如果觉得不喜欢，可以自行在 issue 及网络中搜索更换数学公式字体的方法

3. 这是 LaTeX 与数学字体的使用问题，和模板无关。首先请明白，通常意义下，italic/斜体字母表示变量，我猜测你示例中 `SI` 与 `TH` 应该是专有名词等的缩写，本身就不应放在数学环境中，请查看[主要符号表](https://github.com/obster-y/XJTU-thesis/tree/dev/LaTeX_Template#%E4%B8%BB%E8%A6%81%E7%AC%A6%E5%8F%B7%E8%A1%A8)。如果不是这样，请根据[此提问](https://tex.stackexchange.com/questions/6087/two-letter-variable-names)自行查找解决方案

4. 你的提问没有提供有效信息，因此只能建议，首先清除辅助文件，然后检查 log 是否有 biber 的输出。
