### ISSUE TITLE
word另存为.pdf文件时，页眉出错

### ISSUE THREAD

**Issue by Wastoon** [obster-y/XJTU-thesis#43]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「MacOS」
 - Word 版本：「2016」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
在word中**_另存为文件为.pdf_**时，导出的.pdf的页眉出现错误【Error! Use the Home tab to apply 标题 1 to the text that you want to appear here.Error! Use the
Home tab to apply 标题 1 to the text that you want to appear here.】下图中，左边是word中可以正常显示页眉，右边是.pdf文件无法正常显示页眉。

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/31173581/160079638-db47fd9b-bf65-4c0a-a9a3-131ad90f1663.png">

**其他说明**

**Comment by Wastoon** [comment]
> 

嗯嗯，麻烦您了，我这边打开的就是仓库里dev分支提供的原始.dotm格式文件，然后将其保存为.docx文件，最后另存为.pdf文件。下面附上我的.docx文件和.pdf文件【链接:https://pan.baidu.com/s/1olWiwdeZFry9ZQNzqhe3ow  密码:ulqn】

**Comment by obster-y** [comment]
我在我的主机上 使用我上传的 .dotm 和你提供的 .docx，使用「另存为」「打印」「导出为PDF/XPS」三项功能均没有出现所示情况。

猜测可能与 MacOS 有关？

建议直接使用「打印为」，不要另存或者导出，应该能初步解决问题

**Comment by sikouhjw** [comment]
1. github 是可以直接上传文件的
2. 应该是跟语言版本有关，参考《如何解决Error! Use the Home tab to apply 标题 1 to the text that you want to appear here.》[^1]
3. 自行确认下『标题 1』是不是叫『标题 1』？有可能你用的是英文版

[^1]: https://zhidao.baidu.com/question/198428085799225125.html

**Comment by Wastoon** [comment]
> 

我想也是机器平台的问题，我试过打印保存为.pdf，这样是没有问题的。可是打印保存成.pdf中所有的点击跳转超链接又会失效【欲哭无泪】后面如果我还是不能解决的话，就打算用win10啦，这样应该就没问题了

**Comment by Wastoon** [comment]
> 1. github 是可以直接上传文件的
> 2. 应该是跟语言版本有关，参考《如何解决Error! Use the Home tab to apply 标题 1 to the text that you want to appear here.》[1](#user-content-fn-1-5cbfe7d4d63bcec021afcc5d6d8729d3)
> 3. 自行确认下『标题 1』是不是叫『标题 1』？有可能你用的是英文版
> 
> ## Footnotes
> 1. https://zhidao.baidu.com/question/198428085799225125.html [↩](#user-content-fnref-1-5cbfe7d4d63bcec021afcc5d6d8729d3)

1. 抱歉呐，不过学到了，谢谢大神
2. 我试过更高mac的语言，重启后仍然不可以
3. 确认后是叫『标题 1』，如下图：
<img width="578" alt="image" src="https://user-images.githubusercontent.com/31173581/160089116-4e2bea8c-8792-42b7-ac30-ea68dc3a30dc.png">
我想后面如果我还是不能解决的话，就打算用win10啦，这样应该就没问题了，感谢大神回复，瑞思拜

**Comment by sikouhjw** [comment]
>     2. 我试过更高mac的语言，重启后仍然不可以

我说的是 Word 的版本语言，可能你的版本是英文版。

>     3. 确认后是叫『标题 1』，如下图：

样式那里也叫『标题 1』吗？英语版也许是『title』。

**Comment by Wastoon** [comment]
> 
我这边Macos的Office是在学校的正版软件中心下载的，版本方面我是不太清楚的，但希望下面的解决办法能对存在相同魔性问题的同学有帮助。
【解决办法来了（或许不优美）】参考[https://answers.microsoft.com/zh-hant/msoffice/forum/all/word-2013/b77693ac-4891-4c12-bdff-a86dceac7d0d](url)的解决办法。
1. 把word里面显示域代码打开（alt+F9）后，将页眉处的代码进行如下修改（去除「标题」两个字即可）：
修改前：
<img width="543" alt="image" src="https://user-images.githubusercontent.com/31173581/160220444-defc30dc-76f8-4d37-9f54-ec525a5652b0.png">
修改后：
<img width="494" alt="image" src="https://user-images.githubusercontent.com/31173581/160220469-d5840808-2bdd-499e-9976-1cc920c89665.png">

2. 经过步骤1后，word另存为.pdf后，所有章节的奇数页页眉都能正常显示序号+标题了，但不希望出现标题的摘要，符号表，致谢，参看文献等章节前会出现编号0，这一步就来解决它。（我这里的方法感觉不太优美，希望仓库大佬们帮忙优化）
a. 具体的，先添加分节符｜将文本隔离为【摘要】｜【符号表】｜【正文】｜【致谢】｜【参考文献】｜【后面剩下的】
b. 再将不需要页眉处显示编号的章节如【摘要】，【符号表】，【正文】，【致谢】，【参考文献】，【研究成果】，【评阅人名单】的页眉修改为下图就完成了：
<img width="347" alt="image" src="https://user-images.githubusercontent.com/31173581/160220750-8384f902-ee82-4877-9110-bc5d36735478.png">
