### ISSUE TITLE
英文字母与希腊字母粗斜体

### ISSUE THREAD

**Issue by ymzang** [obster-y/XJTU-thesis#45]
校友你好，使用模板中发现无法将希腊字母（比如`\theta`）进行加粗，已测试如下两种办法：

1. 在cls文件中使用`\RequirePackage{bm}`添加bm宏包，然后在正文中使用`\bm`命令，但编译不通过；
2. 使用`\emph{\mathbf{\theta}}`，亦无法编译通过。

请问此问题应该如何解决？

**Comment by obster-y** [comment]
1. 如果你没有看过[「提问前必读」](https://github.com/obster-y/XJTU-thesis/issues/35)，请先查看此内容
2. 如果你看过「提问前必读」，请按照其中的提到的内容自行搜索解决方案，因为我可以确定这个问题在 issue，README，以及示例的 .tex 中都提到了
3. 如果你确实在上述文件中搜索了但没有搜索到，可以提供你搜索的关键词

**Comment by ymzang** [comment]
不好意思，是我问题没有表述清楚。是准备用**粗斜体**（英文字母和希腊字母）表示向量。
README中提到使用`\mathbf`命令，但此命令只能实现加粗，但不能同时实现斜体功能。

**Comment by obster-y** [comment]
我非常确定你还是没有搜索或仔细查看 dev 分支的「使用手册.pdf」

https://github.com/obster-y/XJTU-thesis/blob/6b9fb3aff3f6c38f77b7addd2912b22e4e287d18/LaTeX_Template/Main_Spine/c1.tex#L166

**Comment by ymzang** [comment]
你好，前几天处理了一些别的事情，同时也测试了不同的模板。
看到作者你的回复，确实在新的dev分支解决了这个问题。但是我写作时用的是研究生院的版本（1.2.7），其中希腊字母粗斜体问题无法解决。将原来的部分文件复制到dev分支版本，又出现了一些其他的编译问题。目前为止，这块我还不知道解决办法。
