### ISSUE TITLE
[BUG] [TeX] Latex模板中的逗号与word模板中逗号差异较大

### ISSUE THREAD

**Issue by WujiangXu** [obster-y/XJTU-thesis#47]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「overleaf」
 - TeX 编译方式：「xelatex+biber」
 - Word 版本：「2016 / 2019 / 365 / 2021 / ...」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
latex模板生成的逗号视觉上与word模板生成的差距较大。

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**

![image](https://user-images.githubusercontent.com/32159528/162174343-3669ef8e-5b90-4ede-ae23-67c7362222b2.png)
![image](https://user-images.githubusercontent.com/32159528/162174393-635bd059-9eb8-48e4-8c53-1052f7eb69b3.png)

**其他说明**

**Comment by sikouhjw** [comment]
https://github.com/obster-y/XJTU-thesis/blob/6b9fb3aff3f6c38f77b7addd2912b22e4e287d18/LaTeX_Template/XJTU-thesis.cls#L258-L284
word 用的是『中易宋体』，Overleaf 上没有，所以用的是『fandol 宋体』。

最后终稿让用 windows 的同学编译即可。
