### ISSUE TITLE
中英文摘要分别都占两页，word模板中各占一页

### ISSUE THREAD

**Issue by wwwei1997** [obster-y/XJTU-thesis#48]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「TeXedit」
 - TeX 编译方式：「xelatex+biber」
 - Word 版本：「2016 / 2019 / 365 / 2021 / ...」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
摘要只有一页的话会多出一页空白页，与word模板不一致

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
非必要不要上传代码截图

**其他说明**

**Comment by sikouhjw** [comment]
1. LaTeX 没必要和 Word 一样
2. Word 的章节没有从奇数页开始纯粹是技术原因
3. chapter 默认从奇数页开始，这是排版的行规
4. LaTeX 模板已经得到学位办的承认，没必要纠结这些东西

**Comment by obster-y** [comment]
https://github.com/obster-y/XJTU-thesis/issues/10#issuecomment-973770019
