### ISSUE TITLE
物理量的符号应是斜体，但是模板中使正体字母，斜体如何实现

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#49]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「 dev分支最新」
 - TeX 编辑器：「VS Code」
 - TeX 编译方式：「latexmk 」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
物理量的符号应是斜体，但是模板中使正体字母，斜体应该如何实现

**错误截图**
![image](https://user-images.githubusercontent.com/55922272/162623982-9040fec6-a86e-48c8-b551-256a0736bb1e.png)

**其他说明**

**Comment by obster-y** [comment]
没错，物理量的符号是斜体，而你框出来的是「单位」

**Comment by Gausx** [comment]
I/A 中I应该是物理量把 I需要斜体

**Comment by Gausx** [comment]
> 没错，物理量的符号是斜体，而你框出来的是「单位」
> 
> > _L_=2m 是长度(物理量) 等于 2 米(单位)

I/A 中I应该是物理量把 I需要斜体

**Comment by obster-y** [comment]
明白你的意思了，是个 Bug，不好意思
