### ISSUE TITLE
TeXLive 2019 版本可能导致的问题

### ISSUE THREAD

**Issue by realolin** [obster-y/XJTU-thesis#50]
你好，我是个latex新手，想使用这个模板，但一直出现如下图的报错，请问一下该怎么处理，谢谢！
![2022-4-11 11-6-56](https://user-images.githubusercontent.com/58211653/162658997-e9de01e1-a0b7-4784-beef-8ed118ccfd38.png)

**Comment by sikouhjw** [comment]
不支持 texlive 2019

**Comment by realolin** [comment]
> 不支持 texlive 2019

使用说明里写着2019可以啊

**Comment by obster-y** [comment]
master 分支支持 2019，dev 不支持，不好意思没有说清楚

**Comment by realolin** [comment]
> master 分支支持 2019，dev 不支持，不好意思没有说清楚

谢谢，不过我用的就是master分支的模板

**Comment by obster-y** [comment]
这样的话，还是建议安装 2020 或着 2021，我会再在 2019 测试一下

**Comment by realolin** [comment]
好的，谢谢了，还是希望能在2019上用，我一装后面的版本，过去期刊论文用的模板就报错……
