### ISSUE TITLE
正文中交叉引用内容和前后正文间距

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#53]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「 VS Code 」
 - TeX 编译方式：「latexmk」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
为了实现图 xxx 正文功能
使用了
`
\crefformat{subfigure}{子图~#2#1#3~}
\crefformat{figure}{图~#2#1#3~}
\crefformat{table}{表~#2#1#3~}
\crefformat{algorithm}{算法~#2#1#3~}
\crefformat{listing}{源码~#2#1#3~}
`

**其他说明**

不确定xxx后和正文是否需要空格，但感觉图和xxx有空格，后边也应该有，只是建议。

**Comment by obster-y** [comment]
1. 因为我没有发现任何学校给出的题注内标签和编号间距离的具体格式要求，因此这里的格式如果自己不满意，可以自己改
2. 我认为你是说，因为题注内标签和编号有空格（实际上确实有），所以编号和后面正文也要有空格，那么在你 patch 之前，这个要求已经实现了，你可以自己查看「使用手册.pdf #4.1 基于 Label 的引用」给出的示例，你描述的位置已经有空格了
3. 这个提问表达的不够明白，比较难以理解，我一开始并不明白什么叫做「图 xxx 正文功能」，建议修改为「正文中交叉引用内容和前后正文间距」之类的表述

![20220417_09451650159904_544x363](https://user-images.githubusercontent.com/55270856/163696739-6b43f618-dd12-4f56-b95b-7df6eca2debb.png)

**Comment by Gausx** [comment]
> 3\. 提问表达的不够明白，比较难以理解，我一开始并不明白什么叫做「图 xxx 正文功能」，建议修改为「正文中交叉引用内容和前后正文间距

3已经更改。对于2我看到示例中手动进行了空格，刚开始我也是这样，但是我感觉改到统一配置里边更合适，以防万一后边更改方便。个人比较这样建议

**Comment by obster-y** [comment]
明白你的意思了，我还是决定不改，不过这个建议之后会加入使用说明，空格留给用户决定。
