### ISSUE TITLE
\mathcal命令字体问题

### ISSUE THREAD

**Issue by ymzang** [obster-y/XJTU-thesis#54]
作者你好：
已看到最新的使用手册中提到“不建议使用`\mathcal`命令输入，可能会出现字体问题……”。
但我之前的文章中，大量使用了此命令，已较为习惯。我用最新的`XJTU-thesis.cls`进行编译，确实出现了字体问题。
因此请问如果想继续使用`\mathcal`命令，如何解决字体问题？

**Comment by obster-y** [comment]
https://tex.stackexchange.com/questions/578372/i-cant-put-accent-on-mathcal-after-changing-the-font-of-mathcal

**Comment by obster-y** [comment]
如果你确定是字体问题，请提供相关的信息，比如 .log 文件之类的

**Comment by ymzang** [comment]
你好，我LaTeX学的不多，看.log文件没有看出相关的信息。不过可将问题描述一下。
1. 使用1.2.7的.cls文件，使用\boldsymbol命令加粗\theta，没有粗斜体效果，但在这个.cls版本下，\mathcal{H}显示是正常的。如下图所示：
![旧问题](https://user-images.githubusercontent.com/24860976/163753254-9c15ad79-5f6c-4544-bd32-1b8828362bf4.png)
2. 使用新的.cls文件，同样使用\boldsymbol命令加粗\theta，显示是正常的。但\mathcal{H}的显示异常了，但我LaTeX学得不深，定位不到具体问题。
![新问题](https://user-images.githubusercontent.com/24860976/163753390-85f1846e-8fe1-4e80-83d6-10a6aa90bd02.png)

**Comment by sikouhjw** [comment]
1. `\boldsymbol` 不推荐使用
2. 参考 https://github.com/whutug/whu-thesis/issues/120#issuecomment-1098202920 ，这是 unicode-math 的特性，可以改，但也可以不改
