### ISSUE TITLE
参考文献中文献题名大小写问题

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#55]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021 」
 - 模板版本：「dev分支最新 」
 - TeX 编辑器：「VS Code 」
 - TeX 编译方式：「latexmk」
 - Word 版本：「 365 」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
从谷歌学术或者其他地方复制过来的bibtex中的title中好多每个单词首字母都是大写，但是我大致翻看国标好像应该是小写，除了特殊的单词。想问下如何统一设置为文献题目除了只有首字母大写，剩下全部小写。如果有大写自己单独用大括号括起来。

**Comment by obster-y** [comment]
1. 没明白，请给截图和.bib示例
2. 如果是谷歌学术或者源文件的文本本身的问题，那就和 biblatex 无关

**Comment by sikouhjw** [comment]
![图片](https://user-images.githubusercontent.com/49770925/164142027-dd7c953c-dbdb-46ac-a3c0-19996053c93d.png)
建议你多看国标
