### ISSUE TITLE
[BUG] [TeX/Word] 标题间距与word不一致

### ISSUE THREAD

**Issue by xing641** [obster-y/XJTU-thesis#56]
// 抱歉，赶时间，没按格式来

1. latex版本的一级标题的上下间距，比word版要小。（主要体现在摘要过于靠页眉）
2. latex版本的页眉的宽度比word版要大。（不是很重要）

**Comment by xing641** [comment]
> // 抱歉，赶时间，没按格式来
> 
> 1. latex版本的一级标题的上下间距，比word版要小。（主要体现在摘要过于靠页眉）
> 2. latex版本的页眉的宽度比word版要大。（不是很重要）

latex是dev版本

**Comment by obster-y** [comment]
抱歉，不论是否赶时间，请按照模板格式提问，不会因为赶时间而特别对待，同时请阅读「提问前必读」，你的问题在之前的 issue 中出现过。
