### ISSUE TITLE
[BUG] [TeX/Word] 一级标题间距问题

### ISSUE THREAD

**Issue by xing641** [obster-y/XJTU-thesis#57]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「VS Code」
 - TeX 编译方式：「xelatex+biber」
 - Word 版本：「2021」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
// 非常抱歉

1. 一级标题的间距过短。
2. 搜索过历史issue，里面只有关于1.2.7版本的回答。此外还有一个关于不要在意行间距的回答。
3. 发现在dev分支中我编译的结果和使用手册不一致，但是使用手册似乎不是最新的版本生成的，不确定是我本地环境的问题还是版本的问题。（详见错误截图。编译1.2.7没有问题）

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
![image](https://user-images.githubusercontent.com/19240234/164593407-c205f7ec-d4dd-4bb8-9f3e-7d6b9e22a589.png)

**其他说明**

**Comment by obster-y** [comment]
「使用手册.pdf」是二进制文件，所以请不要和使用手册进行对比

**Comment by obster-y** [comment]
和 word 生成的 pdf 相比，有部分间距区别，但还没有在格式审查时遇到问题

**Comment by xing641** [comment]
> 

多谢，我还想最后确定一下是我本地环境的问题还是dev版本的问题。

另：如果我生成版本没有错误，我还是建议将摘要和一级标题的行距修改一下，原来的还是更好看点。。。

和word生成的pdf对比：

![image](https://user-images.githubusercontent.com/19240234/164598971-57d6fa5e-71a4-4107-8095-b22019a33dc7.png)


![image](https://user-images.githubusercontent.com/19240234/164599935-23cf1d4a-9abb-4c1b-af0f-546d6d2b9d56.png)

**Comment by obster-y** [comment]
我的 word 生成的 pdf 并不是这样
![1](https://user-images.githubusercontent.com/55270856/164601901-4cb1f275-2b9f-44af-8730-30cbdc60fe23.png)

**Comment by xing641** [comment]
> 我的 word 生成的 pdf 并不是这样 ![1](https://user-images.githubusercontent.com/55270856/164601901-4cb1f275-2b9f-44af-8730-30cbdc60fe23.png)

1. 确实，我是在1.2.7里面提供的word生成的版本，对比发现你这是dev里面提供的word版本，可能有差别。虽然都叫2021版。。。

2. 于是我从[官网](http://gs.xjtu.edu.cn/info/1209/7605.htm)下了2021版，据比对，跟1.2.7里面的word是一个版本。

3. dev版本生成的字体行间距是参照官网word的行间距来的。之前也有关于word模板版本的讨论，有空可以统一。

4. 既然不会有问题，也不深究了，格式问题如果没有具体说明，确实很难统一。

**Comment by obster-y** [comment]
如果想要自己调整，可以自行修改 .cls
https://github.com/obster-y/XJTU-thesis/blob/35cceda1972c39be3219d275a5dbd70bfbe2d9f4/LaTeX_Template/XJTU-thesis.cls#L703-L709
