### ISSUE TITLE
[BUG] [TeX] 多行图注、表注格式问题

### ISSUE THREAD

**Issue by llan-ml** [obster-y/XJTU-thesis#58]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 / Win 7 / MacOS / Linux发行版 / ...」 Win 10
 - TeX 发行版：「TeXLive 2021 / MikTeX / CTeX / ...」TeXLive 2021
 - 模板版本：「1.2.7(master分支) / dev分支最新 / ...」dev分支最新
 - TeX 编辑器：「TeXStudio / WinEdt / VS Code / ...」Sublime
 - TeX 编译方式：「latexmk / xelatex+biber / pdflatex / ...」xelatex + biber

**Bug 说明（每项非必需填写，请尽量明了易懂）**
Word模版中多行图注表注如下所示：
![image](https://user-images.githubusercontent.com/22030149/164874857-38a3aa91-3957-4a77-a5f2-a7f50eb480c5.png)
![image](https://user-images.githubusercontent.com/22030149/164874891-558c723e-492a-447e-a73c-98b71f23e902.png)

Latex模板中生成的多行图注如下所示：
![image](https://user-images.githubusercontent.com/22030149/164874966-147aff97-3fb1-4f79-b91b-be8b9e0ffa67.png)

Latex模板中的多行表注也存在类似的问题。

另外，word模板中图注、表注有1.2倍行距，Latex模板中没有。

**Comment by obster-y** [comment]
参考问答：https://github.com/tuna/thuthesis/issues/589
