### ISSUE TITLE
参考文献的格式问题

### ISSUE THREAD

**Issue by JinglezZ** [obster-y/XJTU-thesis#6]
您好，在这个模板的参考文献中，英文文献的作者名称全部是大写的，但是在 word 版本的模板中英文名只有首字母大写。请问这种格式是和图书馆/学位办老师商量后得到认可的吗？

**Comment by sikouhjw** [comment]
国标就是全大写的

**Comment by JinglezZ** [comment]
> 国标就是全大写的

所以您有没有和图书馆/学位办老师沟通过，完全按照国标书写是可以通过格式审查的吗？谢谢您！

**Comment by sikouhjw** [comment]
> 
> 
> > 国标就是全大写的
> 
> 所以您有没有和图书馆/学位办老师沟通过，完全按照国标书写是可以通过格式审查的吗？谢谢您！

https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/README.md?plain=1#L9-L14

**Comment by JinglezZ** [comment]
> > > 国标就是全大写的
> > 
> > 
> > 所以您有没有和图书馆/学位办老师沟通过，完全按照国标书写是可以通过格式审查的吗？谢谢您！
> 
> https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/README.md?plain=1#L9-L14

好的，非常感谢您！

**Comment by obster-y** [comment]
> 您好，在这个模板的参考文献中，英文文献的作者名称全部是大写的，但是在 word 版本的模板中英文名只有首字母大写。请问这种格式是和图书馆/学位办老师商量后得到认可的吗？

这里的冲突在与 Word 模板要求了「按照国标」，而它自己的示例不是国标，所以我个人认为更应该去向他们提问，为什么自己发布的模板可以前后不一致。

另外，我之前就在这里提到了。
https://github.com/obster-y/XJTU-thesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE

最后，这已经发布在学位办网上了，所以可以认为这样是可以的。

**Comment by JinglezZ** [comment]
> > 您好，在这个模板的参考文献中，英文文献的作者名称全部是大写的，但是在 word 版本的模板中英文名只有首字母大写。请问这种格式是和图书馆/学位办老师商量后得到认可的吗？
> 
> 这里的冲突在与 Word 模板要求了「按照国标」，而它自己的示例不是国标，所以我个人认为更应该去向他们提问，为什么自己发布的模板可以前后不一致。
> 
> 另外，我之前就在这里提到了。 https://github.com/obster-y/XJTU-thesis#%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE
> 
> 最后，这已经发布在学位办网上了，所以可以认为这样是可以的。

好的，我之前也去问过我们学院格式审查的老师了，老师说他以前也关于学校官方模板中前后矛盾的地方问过学位办，他们也只是回了一些模棱两可的官话。我也是在学位办官网上首先下载到的您的模板，只是有点不放心所以来确认一下。我之前用了 XJTU-Thesis-Template 这个模板几乎已经把学位论文写完了，最近才发现有新的模板。。。您在新模板里面的改动实在太击中痛点了，老模板的 subfigure 环境太落后太不好用了

**Comment by Gausx** [comment]
> > > 国标就是全大写的
> > 
> > 
> > 所以您有没有和图书馆/学位办老师沟通过，完全按照国标书写是可以通过格式审查的吗？谢谢您！
> 
> https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/README.md?plain=1#L9-L14

想额外的问下如果我想对于姓氏修改为Qian 第一个大写后边小写，应该如何更改底层的代码？

**Comment by Gausx** [comment]
> > > > > 国标就是全大写的
> > > > 
> > > > 
> > > > 所以您有没有和图书馆/学位办老师沟通过，完全按照国标书写是可以通过格式审查的吗？谢谢您！
> > > 
> > > 
> > > https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/README.md?plain=1#L9-L14
> > 
> > 
> > 想额外的问下如果我想对于姓氏修改为Qian 第一个大写后边小写，应该如何更改底层的代码？
> 
> 在 `\documentclass` 前面加上
> 
> ```
> \PassOptionsToPackage{gbnamefmt=lowercase}{biblatex}
> ```

万分感谢您的回答

**Comment by zwq869974732-byte** [comment]
中文全角，英文半角该怎么修改

**Comment by Gausx** [comment]
> 中文全角，英文半角该怎么修改

建议问一下AI 应该会快很多
