### ISSUE TITLE
[BUG] [TeX] 打印店检查出来的问题

### ISSUE THREAD

**Issue by kamiLight** [obster-y/XJTU-thesis#62]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x ] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 / Win 7 / MacOS / Linux发行版 / ...」 Win10
 - TeX 发行版：「TeXLive 2021 / MikTeX / CTeX / ...」TeXLive 2021
 - 模板版本：「1.2.7(master分支) / dev分支最新 / ...」 dev分支最新 
 - TeX 编辑器：「TeXStudio / WinEdt / VS Code / ...」VS Code 
 - TeX 编译方式：「latexmk / xelatex+biber / pdflatex / ...」latexmk 
 - Word 版本：「2016 / 2019 / 365 / 2021 / ...」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
前几天去创新港校区的打印店，然后工作人员给我指出的一些问题。我也不确定这些问题是不是都需要改，可能有的就是正确的，所以我都写出来了。如果需要修改的话，最好能给出具体的修改方法，非常感谢！

1. 英文关键词和论文类型中间需要空一行
![image](https://user-images.githubusercontent.com/46705365/168536123-b5fb50ce-12b9-4b8c-b024-270d920e16ec.png)

2. 答辩委员会中，“（注：主席）”这部分字体颜色要用红色
![2022-05-16_145642](https://user-images.githubusercontent.com/46705365/168537633-02f7d66d-f6d5-4d90-90da-a5b3973c91df.png)

3. 图片的段后间距应该是0.5行，打印店说我的比0.5行要大
![2022-05-16_150013](https://user-images.githubusercontent.com/46705365/168537672-a1e478e7-b62a-45c4-b0c9-9ab9a1c5950b.png)

4. 表注应该是段后0行，打印店说我的这部分间距有点大
![2022-05-16_150139](https://user-images.githubusercontent.com/46705365/168537709-a026e232-4722-4d90-aa35-b3b9688983d3.png)

5. 一级标题的段前和段后间距过小
![2022-05-16_150739](https://user-images.githubusercontent.com/46705365/168537789-87ceeb8c-a15e-4e72-90b9-417d2a6023f1.png)

**Comment by obster-y** [comment]
均已修复，请 pull 后清除临时文件重新编译即可

**Comment by kamiLight** [comment]
上述的问题都被解决了，但是发现了一个新的问题，表注的段前间距应该是0.5行，现在貌似是被改没了
![image](https://user-images.githubusercontent.com/46705365/168628276-c8535493-74e5-4d39-adff-0a09f9c0a1ee.png)

**Comment by obster-y** [comment]
昨天没仔细测试，现在应该正常了

**Comment by kamiLight** [comment]
非常感谢回复，但我还有几个小问题。
1. 表和表后正文的间距貌似比0.5行要大
2. 图和图注的间距好像比0.5行要小

麻烦您那边再确认一下，感谢

**Comment by Gausx** [comment]
![image](https://user-images.githubusercontent.com/55922272/168878672-53e4cf20-cbd4-45ff-8dac-79770197cdfb.png)
感觉好像子图标题和主标题距离过远

**Comment by obster-y** [comment]
> 

Word 和 LaTeX 的间距定义是不一样的，因此我不会拿游标卡尺一边量一边继续改，如果有需要可以自己修改 cls 文件

**Comment by obster-y** [comment]
> ![image](https://user-images.githubusercontent.com/55922272/168878672-53e4cf20-cbd4-45ff-8dac-79770197cdfb.png) 感觉好像子图标题和主标题距离过远

是的，改了
