### ISSUE TITLE
参考文献需要姓名开头大写，后面小写（盲审意见）

### ISSUE THREAD

**Issue by jacky123465** [obster-y/XJTU-thesis#63]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「1.2.7(master分支) 」
 - TeX 编辑器：「TeXStudio /」
 - TeX 编译方式：「xelatex+biber 」

**错误截图**
![image](https://user-images.githubusercontent.com/22407341/168573234-548d23fe-f012-4bf8-bb8a-d2e8aea6c808.png)

**其他说明**
请问一下如何设置成小写呢

**Comment by LouisYZK** [comment]
> **必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
> 
> * [x]  已搜索过历史 issue
> * [x]  已搜索过已经关闭的 issues
> 
> **软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
> 
> * 操作系统：「Win 10 」
> * TeX 发行版：「TeXLive 2021」
> * 模板版本：「1.2.7(master分支) 」
> * TeX 编辑器：「TeXStudio /」
> * TeX 编译方式：「xelatex+biber 」
> 
> **错误截图** ![image](https://user-images.githubusercontent.com/22407341/168573234-548d23fe-f012-4bf8-bb8a-d2e8aea6c808.png)
> 
> **其他说明** 请问一下如何设置成小写呢

对于这个问题，真的无力吐槽学校给的那个模板说明。国标 GB/T 7714-2015 明明给的示例就是用汉语拼音书写的人名，姓全大写，其名可缩写。不知道交大用的是啥标准，莫名其妙。

你可以用参数`gbnamefmt=lowercase` 解决。

**Comment by jacky123465** [comment]
> > **必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
> > 
> > * [x]   已搜索过历史 issue
> > * [x]   已搜索过已经关闭的 issues
> > 
> > **软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
> > 
> > * 操作系统：「Win 10 」
> > * TeX 发行版：「TeXLive 2021」
> > * 模板版本：「1.2.7(master分支) 」
> > * TeX 编辑器：「TeXStudio /」
> > * TeX 编译方式：「xelatex+biber 」
> > 
> > **错误截图** ![image](https://user-images.githubusercontent.com/22407341/168573234-548d23fe-f012-4bf8-bb8a-d2e8aea6c808.png)
> > **其他说明** 请问一下如何设置成小写呢
> 
> 对于这个问题，真的无力吐槽学校给的那个模板说明。国标 GB/T 7714-2015 明明给的示例就是用汉语拼音书写的人名，姓全大写，其名可缩写。不知道交大用的是啥标准，莫名其妙。
> 
> 你可以用参数`gbnamefmt=lowercase` 解决。

请问一下是在哪个BST文件里面呢

**Comment by LouisYZK** [comment]
> > > **必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
> > > 
> > > * [x]    已搜索过历史 issue
> > > * [x]    已搜索过已经关闭的 issues
> > > 
> > > **软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
> > > 
> > > * 操作系统：「Win 10 」
> > > * TeX 发行版：「TeXLive 2021」
> > > * 模板版本：「1.2.7(master分支) 」
> > > * TeX 编辑器：「TeXStudio /」
> > > * TeX 编译方式：「xelatex+biber 」
> > > 
> > > **错误截图** ![image](https://user-images.githubusercontent.com/22407341/168573234-548d23fe-f012-4bf8-bb8a-d2e8aea6c808.png)
> > > **其他说明** 请问一下如何设置成小写呢
> > 
> > 
> > 对于这个问题，真的无力吐槽学校给的那个模板说明。国标 GB/T 7714-2015 明明给的示例就是用汉语拼音书写的人名，姓全大写，其名可缩写。不知道交大用的是啥标准，莫名其妙。
> > 你可以用参数`gbnamefmt=lowercase` 解决。
> 
> 请问一下是在哪个BST文件里面呢

`\RequirePackage[hyperref=true,backend=biber,defernumbers=true,style=gb7714-2015,gbalign=left,gbpub=false,gbnamefmt=lowercase]{biblatex}`

**Comment by jacky123465** [comment]
> 

![image](https://user-images.githubusercontent.com/22407341/168605648-0afafe0a-686a-4be1-975c-ba1440c78f6e.png)
貌似没有解决，已经删除掉多余文件重新编译。

代码如下（main.tex）
`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 如果有使用其他包，请在这里添加
%% If you need other packages, use them here

% \usepackage{}
\usepackage{amssymb}
\usepackage{url}
\RequirePackage[hyperref=true,backend=biber,defernumbers=true,style=gb7714-2015,gbalign=left,gbpub=false,gbnamefmt=lowercase]{biblatex}

\def\UrlBreaks{\do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J  
	\do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T\do\U\do\V  
	\do\W\do\X\do\Y\do\Z\do\[\do\\\do\]\do\^\do\_\do\`\do\a\do\b  
	\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j\do\k\do\l\do\m\do\n  
	\do\o\do\p\do\q\do\r\do\s\do\t\do\u\do\v\do\w\do\x\do\y\do\z  
	\do\.\do\@\do\\\do\/\do\!\do\_\do\|\do\;\do\>\do\]\do\)\do\,  
	\do\?\do\'\do+\do\=\do\#}  `

**Comment by jacky123465** [comment]
> 你确定你看过历史 issue 了？
> 
> 建议你在 issue 搜索关键词「参考文献」 然后从最早的 issue 看起

您好。我之前搜过，历史中确实有这个问题，但是好像没有解决，主要是盲审老师提的意见，我不敢不改
