### ISSUE TITLE
声明页问题

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#64]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10.」
 - TeX 发行版：「TeXLive 2021
 - 模板版本：「dev分支最新 」
 - TeX 编辑器：「 VS Code 」
 - TeX 编译方式：「latexmk」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
声明页与最新的word版本不同，搜索过历史请问第二个图片问题可以确定了吗？1 和3  的问题麻烦看下

**错误截图**
1.
![image](https://user-images.githubusercontent.com/55922272/169426305-fcc37234-f326-4d77-9582-df8085b5c88b.png)
2. 研究生后是否有名字
![image](https://user-images.githubusercontent.com/55922272/169426346-e587363f-36aa-4278-b81d-9dbe905d9770.png)
3. 空白间隔有点明显不同
![image](https://user-images.githubusercontent.com/55922272/169426394-d9160746-8814-425d-8e5a-695c9cca2536.png)

**其他说明**

**Comment by obster-y** [comment]
1. 3. 已修改
2. 在查看 2018 2019 年的论文时，是有这一处空白的，考虑到 Word 模板的质量不高，我认为删除这一空白是不合理的。可以看出独创性声明（2）是针对导师的，而这一句「确系在本人指导下由该生独立完成的研究成果」中「该生」是谁？如果前面没有空白，即「研究生」的同位语，那么这一主体就不明确。同时学位办没有给出回复，因此我倾向于保留这一空白。在未给出明确回复前，如果有需要，请自行修改 XJTU-thesis.cls 文件。

**Comment by Gausx** [comment]
> 1. / 3. 已修改
> 2. 在查看 2018 2019 年的论文时，是有这一处空白的，考虑到 Word 模板的质量不高，我认为删除这一空白是不合理的。可以看出独创性声明（2）是针对导师的，而这一句「确系在本人指导下由该生独立完成的研究成果」中「该生」是谁？如果前面没有空白，即「研究生」的同位语，那么这一主体就不明确。同时学位办没有给出回复，因此我倾向于保留这一空白。在未给出明确回复前，如果有需要，请自行修改 XJTU-thesis.cls 文件。 [几个与word版论文模板不一致的地方 #10](https://github.com/obster-y/XJTU-thesis/issues/10)

好的谢谢

**Comment by notomatoes** [comment]
声明页要在奇数页 ，应该修改哪里

**Comment by sikouhjw** [comment]
> 声明页要在奇数页 ，应该修改哪里

https://github.com/obster-y/XJTU-thesis/blob/11bf5fbeba86b428c89f9d3a525030d8cdf06bb8/LaTeX_Template/XJTU-thesis.cls#L221-L228
