### ISSUE TITLE
[TeX] 打印店所提出的一些格式问题

### ISSUE THREAD

**Issue by Givyuscss** [obster-y/XJTU-thesis#66]
1. 每页正文与页眉的间距过大（左为word版，右为latex）
![屏幕截图 2022-05-25 161750](https://user-images.githubusercontent.com/39357309/170215500-f1be6e2b-cc38-49db-93cb-a020d663f833.jpg)

2. 表格以及图像的标号与题目之间需要有两个空格 （左为word版，右为latex）
![屏幕截图 2022-05-25 162042](https://user-images.githubusercontent.com/39357309/170216101-2acd4c9c-f050-4c05-967a-57a730eb6081.jpg)

3. 中英文摘要后不空页

一些修改建议：
1. 目录中间隔略小，对比后把1157-1159中间隔改为4pt后与word版本基本一致
`\setlength{\cftbeforechapskip}{3pt}
\setlength{\cftbeforesecskip}{3pt}
\setlength{\cftbeforesubsecskip}{3pt}`

2. 表格以及图像标题与正文的间隔依旧不太对，对比后把783行的`\captionsetup[figure]{aboveskip=-8pt}`改为-5pt并添加`\captionsetup[table]{aboveskip=5pt}`后与word版基本一致

3. 表格后与正文的间隔略小，在表格后添加`\vspace{0.1cm}`基本解决

**Comment by sxwgit** [comment]
同学您好，我也在用这个模板调整论文，我遇见英文字号（包括公式）过粗，字体也不对，不知道你是怎么解决的呢

**Comment by Givyuscss** [comment]
公式应该没问题吧，我看同学word版打印出来的也差不多这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [obster-y/XJTU-thesis] [TeX] 打印店所提出的一些格式问题 (Issue #66)





 
同学您好，我也在用这个模板调整论文，我遇见英文字号（包括公式）过粗，字体也不对，不知道你是怎么解决的呢

**Comment by sxwgit** [comment]
![1653478078(1)](https://user-images.githubusercontent.com/21139332/170251872-c77f32d9-7161-4772-94d2-0ad629032c3e.png)
上图是latex模板的编译结果，下图是word别人的
![ade2be12e809e9548fdbd7665e04ce1](https://user-images.githubusercontent.com/21139332/170252249-a5ba0a07-2ca6-4fc1-a7fe-c8c7ec997a34.jpg)
latex的明显要更粗一点，而且字体与word的也不相同

**Comment by obster-y** [comment]
对于前三个问题：
1. 已修改
2. 刚去印制点问了，空一格或空两格都可以，因为模板没有明确要求，因此不做修改
3. 学校的要求没有明确的规定说明是否英文摘要应该从奇数页开始；空页的原因是在通常情况下，chapter 级的标题都应从奇数页开始；因此空页是为了确保下一章节从奇数页开始；根据我手上看到去年的学位论文，中文摘要只有一页时，英文摘要是从奇数页开始的；我在去年做这个模板时，询问过图书馆的老师，他的答复是“英文摘要可以从奇数页开始，而第一章之后的章节不要求一定从奇数页开始”。因此也不做修改

后续模板是否对其进行更新仍须与学位办确定，现在暂不添加，但是在这里提供修改的方法，有需要请自行修改：
```diff
# 图表 label 后间距：XJTU-thesis.cls 第 777 行
-  labelsep       = space,
+  labelsep       = quad,
# 英文摘要与目录不从奇数页开始：XJTU-thesis.cls 第 1135、1137 行
-  \cleardoublepage
+  %\cleardoublepage
```

对于提出的修改建议，表示感谢。建议中一、二已采纳。

**Comment by obster-y** [comment]
> 同学您好，我也在用这个模板调整论文，我遇见英文字号（包括公式）过粗，字体也不对，不知道你是怎么解决的呢

根据你的描述，如果你想表示，数学字体和 Word 的不一致，那么回答是：因为模板没有规定数学字体的样式，而且在 Word 中使用 Word 原生的 Cambria Math 字体和 Mathtype/AxMath 的 AMS 字体样式也不一样；因此这是一个可选项，而非强制要求。

模板为了保持数学公式字体采用 Times 风格，因此使用了 XITS Math 作为数学公式字体，如果自己非要换一个，请自己寻找相应字体并在下处更改，因此导致的问题不在正常解答范围之内。
https://github.com/obster-y/XJTU-thesis/blob/af3c74add3d1f0048778feddf71aa8d712a4df25/LaTeX_Template/XJTU-thesis.cls#L257-L288
