### ISSUE TITLE
参考文献行间距调整

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#67]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10.」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新 」
 - TeX 编辑器：「VS Code 」
 - TeX 编译方式：「latexmk 」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
请问如何调整参考文献行间距，可以给个代码说明吗？

**Comment by obster-y** [comment]
```shell
texdoc gb7714-2015
```

**Comment by Gausx** [comment]
> ```shell
> texdoc gb7714-2015
> ```
> 
> 另外这种情况，比较建议去 Discussion 区讨论，而不是提交一个「bug issue」

下次注意

**Comment by Gausx** [comment]
> ```shell
> texdoc gb7714-2015
> ```
> 
> 另外这种情况，比较建议去 Discussion 区讨论，而不是提交一个「bug issue」

是否有具体说明，gb7714-2015文档里边主要是文献本身条目问题，好像不涉及文献直接行间距的调整。
![image](https://user-images.githubusercontent.com/55922272/170400619-3a7f020d-5cc3-4558-b27f-6b8fa630be4c.png)
yrl原来写法可以调整这，但是现在的写法没有找到调整的位置
