### ISSUE TITLE
公式环境字母斜体加粗

### ISSUE THREAD

**Issue by JinglezZ** [obster-y/XJTU-thesis#7]
您好，注意到您在使用手册中关于公式书写部分只提供了加粗的方法，即使用 \mathbf，但是对于变量需要斜体加粗的情况您没有给出例子。一般是使用 amsbsy 宏包中的 \boldsymbol 来达成这个效果的，但是我在 main.tex 指定位置中引用该宏包后，\boldsymbol 指令并没有生效，请问是和您引用的别的宏包冲突了吗，或者是别的问题？不好意思又麻烦您了！

**Comment by sikouhjw** [comment]
是 `\setallmainfonts` 的问题，将所有字体设置为 `Times New Roman`，导致无法加粗。
建议模板用 `unicode-math` + `XITS Math`。
https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/XJTU-thesis.cls#L259-L287

**Comment by sikouhjw** [comment]
`\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。
可以使用 `bm` 宏包来生成『伪粗体』。
```tex
% \usepackage{bm}
$\bm{A}A$
```

**Comment by JinglezZ** [comment]
> `\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。 可以使用 `bm` 宏包来生成『伪粗体』。
> 
> ```
> % \usepackage{bm}
> $\bm{A}A$
> ```

您好，\bm 伪粗体尝试了，效果不太好，就是用两个字符的错位产生的效果，稍微放大就能看到重叠的字符。由于工科论文里面难免要用到大量斜体加粗的字符，所以觉得用这种方式会降低阅读的体验。在以前老的模板里，我是采用 newtxtext,newtxmath 这两个仿 tnr 字体来作为英文字体的，虽然和 tnr 有一点差异（不仔细看也找不到区别），但是加粗和斜体的效果更好。您看是不是能考虑在这个模板里也保留用 newtxtext,newtxmath 的选项呢？谢谢！

**Comment by sikouhjw** [comment]
> 不仔细看也找不到区别

1. 我不是模板作者
2. 我不觉得 `newtxtext`、`newtxmath` 好，这两个宏包可能会对设置其它字体产生不可预测的影响
3. 我只支持 `unicode-math` 那套

**Comment by JinglezZ** [comment]
> > > `\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。 可以使用 `bm` 宏包来生成『伪粗体』。
> > > ```
> > > % \usepackage{bm}
> > > $\bm{A}A$
> > > ```
> > 
> > 
> > 您好，\bm 伪粗体尝试了，效果不太好，就是用两个字符的错位产生的效果，稍微放大就能看到重叠的字符。由于工科论文里面难免要用到大量斜体加粗的字符，所以觉得用这种方式会降低阅读的体验。在以前老的模板里，我是采用 newtxtext,newtxmath 这两个仿 tnr 字体来作为英文字体的，虽然和 tnr 有一点差异（不仔细看也找不到区别），但是加粗和斜体的效果更好。您看是不是能考虑在这个模板里也保留用 newtxtext,newtxmath 的选项呢？谢谢！
> 
> 1. 我不是模板作者
> 2. 我不觉得 `newtxtext`、`newtxmath` 好，这两个宏包可能会对设置其它字体产生不可预测的影响
> 3. 我只支持 `unicode-math` 那套

好的，谢谢您，我试试您说的方法，请问是把 \setallmainfonts{Times New Roman}  中的 Times New Roman 替换为 unicode-math 吗？

**Comment by sikouhjw** [comment]
> 
> 
> > > > `\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。 可以使用 `bm` 宏包来生成『伪粗体』。
> > > > ```
> > > > % \usepackage{bm}
> > > > $\bm{A}A$
> > > > ```
> > > 
> > > 
> > > 您好，\bm 伪粗体尝试了，效果不太好，就是用两个字符的错位产生的效果，稍微放大就能看到重叠的字符。由于工科论文里面难免要用到大量斜体加粗的字符，所以觉得用这种方式会降低阅读的体验。在以前老的模板里，我是采用 newtxtext,newtxmath 这两个仿 tnr 字体来作为英文字体的，虽然和 tnr 有一点差异（不仔细看也找不到区别），但是加粗和斜体的效果更好。您看是不是能考虑在这个模板里也保留用 newtxtext,newtxmath 的选项呢？谢谢！
> > 
> > 
> > 
> > 1. 我不是模板作者
> > 2. 我不觉得 `newtxtext`、`newtxmath` 好，这两个宏包可能会对设置其它字体产生不可预测的影响
> > 3. 我只支持 `unicode-math` 那套
> 
> 好的，谢谢您，我试试您说的方法，请问是把 \setallmainfonts{Times New Roman} 中的 Times New Roman 替换为 unicode-math 吗？

不是。不要尝试修改模板，我没修改成功。

**Comment by JinglezZ** [comment]
> > > > > `\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。 可以使用 `bm` 宏包来生成『伪粗体』。
> > > > > ```
> > > > > % \usepackage{bm}
> > > > > $\bm{A}A$
> > > > > ```
> > > > 
> > > > 
> > > > 您好，\bm 伪粗体尝试了，效果不太好，就是用两个字符的错位产生的效果，稍微放大就能看到重叠的字符。由于工科论文里面难免要用到大量斜体加粗的字符，所以觉得用这种方式会降低阅读的体验。在以前老的模板里，我是采用 newtxtext,newtxmath 这两个仿 tnr 字体来作为英文字体的，虽然和 tnr 有一点差异（不仔细看也找不到区别），但是加粗和斜体的效果更好。您看是不是能考虑在这个模板里也保留用 newtxtext,newtxmath 的选项呢？谢谢！
> > > 
> > > 
> > > 
> > > 1. 我不是模板作者
> > > 2. 我不觉得 `newtxtext`、`newtxmath` 好，这两个宏包可能会对设置其它字体产生不可预测的影响
> > > 3. 我只支持 `unicode-math` 那套
> > 
> > 
> > 好的，谢谢您，我试试您说的方法，请问是把 \setallmainfonts{Times New Roman} 中的 Times New Roman 替换为 unicode-math 吗？
> 
> 不是。不要尝试修改模板，我没修改成功。

啊那对于斜体加粗的问题是没有办法了吗，还是等等看模板作者回复呢？

**Comment by obster-y** [comment]
> > > > > > `\boldsymbol` 是调用数学字体中对应的粗体，而 tnr 不是数学字体、没有对应的粗体，导致不能正确加粗。 可以使用 `bm` 宏包来生成『伪粗体』。
> > > > > > ```
> > > > > > % \usepackage{bm}
> > > > > > $\bm{A}A$
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 您好，\bm 伪粗体尝试了，效果不太好，就是用两个字符的错位产生的效果，稍微放大就能看到重叠的字符。由于工科论文里面难免要用到大量斜体加粗的字符，所以觉得用这种方式会降低阅读的体验。在以前老的模板里，我是采用 newtxtext,newtxmath 这两个仿 tnr 字体来作为英文字体的，虽然和 tnr 有一点差异（不仔细看也找不到区别），但是加粗和斜体的效果更好。您看是不是能考虑在这个模板里也保留用 newtxtext,newtxmath 的选项呢？谢谢！
> > > > 
> > > > 
> > > > 
> > > > 1. 我不是模板作者
> > > > 2. 我不觉得 `newtxtext`、`newtxmath` 好，这两个宏包可能会对设置其它字体产生不可预测的影响
> > > > 3. 我只支持 `unicode-math` 那套
> > > 
> > > 
> > > 好的，谢谢您，我试试您说的方法，请问是把 \setallmainfonts{Times New Roman} 中的 Times New Roman 替换为 unicode-math 吗？
> > 
> > 
> > 不是。不要尝试修改模板，我没修改成功。
> 
> 啊那对于斜体加粗的问题是没有办法了吗，还是等等看模板作者回复呢？

不好意思，才看到这个，现在尝试修改

**Comment by JinglezZ** [comment]
补充一个尝试：
我在 XJTU-thesis.cls 文件中把 \setallmainfonts{Times New Roman} 注释掉，然后在 main.tex 中引用 \usepackage{newtxtext,newtxmath} 后，可以正常使用 newtxtext,newtxmath 这两个字体，但是会引起 \cref 指向的错误

**Comment by obster-y** [comment]
> 您好，注意到您在使用手册中关于公式书写部分只提供了加粗的方法，即使用 \mathbf，但是对于变量需要斜体加粗的情况您没有给出例子。一般是使用 amsbsy 宏包中的 \boldsymbol 来达成这个效果的，但是我在 main.tex 指定位置中引用该宏包后，\boldsymbol 指令并没有生效，请问是和您引用的别的宏包冲突了吗，或者是别的问题？不好意思又麻烦您了！

已修复，目前使用 unicode-math + XITS Math 字体。

https://github.com/obster-y/XJTU-thesis/commit/8f6cb111f863cc2d9fc097d121e593b5669abde4#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221

**Comment by JinglezZ** [comment]
> > 您好，注意到您在使用手册中关于公式书写部分只提供了加粗的方法，即使用 \mathbf，但是对于变量需要斜体加粗的情况您没有给出例子。一般是使用 amsbsy 宏包中的 \boldsymbol 来达成这个效果的，但是我在 main.tex 指定位置中引用该宏包后，\boldsymbol 指令并没有生效，请问是和您引用的别的宏包冲突了吗，或者是别的问题？不好意思又麻烦您了！
> 
> 已修复，目前使用 unicode-math + XITS Math 字体。
> 
> [8f6cb11#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221](https://github.com/obster-y/XJTU-thesis/commit/8f6cb111f863cc2d9fc097d121e593b5669abde4#diff-0a5062d54303ac2207aee944a5e6266d99b0c7d35c29d952e1d12320a3939d64R221)

经测试可正常使用，谢谢作者！
