### ISSUE TITLE
[BUG] 打印店指出，英文摘要标题，中英文目录标题上下间距不正确。

### ISSUE THREAD

**Issue by carryyu** [obster-y/XJTU-thesis#70]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：Win 10/MacOS
 - 模板版本：dev分支最新 
 - TeX 编辑器：overleaf
 - TeX 编译方式：xelatex

**Bug 说明（每项非必需填写，请尽量明了易懂）**
英文摘要标题，中英文目录标题上下间距不正确。

**错误截图**
英文摘要标题
<img width="494" alt="英文摘要" src="https://user-images.githubusercontent.com/26600630/170482346-4b324320-6a64-414b-b8a3-e83b7ad3e1d6.png">
中文目录标题
<img width="504" alt="中文目录" src="https://user-images.githubusercontent.com/26600630/170482534-08b1c9d2-1d31-4aac-acfa-c116e7b13ba2.png">
英文目录标题
<img width="496" alt="英文目录" src="https://user-images.githubusercontent.com/26600630/170482625-4b96dd93-98e7-4a6b-bfce-59f3fe8152d2.png">

打印店说中文摘要标题看起来还可以，上面空两行，下面一行，一级标题也都遵循这个规则了，但是上面提到的三个部分明显没有遵循这个规则。请问怎么修改呢？

<img width="503" alt="中文摘要" src="https://user-images.githubusercontent.com/26600630/170482887-edd3ddf6-ba70-4cb9-a644-329f78f6bd51.png">

**Comment by carryyu** [comment]
谢谢，已收到！

**Comment by carryyu** [comment]
我用的应该是最新的dev分支，在macos下用overleaf上的xelatex编译的

**Comment by obster-y** [comment]
现在的问题和系统、编译方式无关，如果你是在 overleaf 用的最新的，也就是说你要么手动复制了最新的 commit 的源码，要么下载下来上传的，要么每次按照 commit 做了同样的修改

上面两张图是今天我截下的图，同样的缩放比例，左边 Word，右边 TeX；所以比较建议你对比一下你使用 .cls 和下面的文件

https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/XJTU-thesis.cls

**Comment by carryyu** [comment]
我是直接把最新分支的zip下载下来，然后倒入overleaf上编译的，cls文件和这个链接对比后是完全一样的。

**Comment by obster-y** [comment]
那么我不清楚为什么会出现这种情况，因为我刚提供的截图表示没有这个问题，也许你自己做了什么修改而忘记了

**Comment by carryyu** [comment]
我对比近期的修改，逐一加入修改后，发现是headsep=0.3cm这个会导致摘要目录等标题上浮。你能否用最新的dev分支在overleaf重新编译一下，看看是否存在这个问题呢？麻烦了

**Comment by carryyu** [comment]
headsep=0.3cm应该是为了每一页开始的边距和word对齐，但是这个貌似会导致一级标题和摘要目录等标题都上浮

**Comment by carryyu** [comment]
左边latex，右边word。
![加之前](https://user-images.githubusercontent.com/26600630/170500199-0645007a-6ad0-43c6-ab35-9f776f6a7b9d.png)
加headsep=0.3cm之前，大标题基本对齐，但是latex标题下多出一行空格，且别的页面开始间距明显大于word版本，如下图所示。
![加之前2](https://user-images.githubusercontent.com/26600630/170500807-8e1691ab-5c9a-4766-bbc4-90988bf2aadf.png)
在加入headsep=0.3cm之后，解决了上述第二个问题，但是一级标题同样上浮了。
![加之后](https://user-images.githubusercontent.com/26600630/170500862-82f402f9-adbe-408d-b6a1-6f07ba3e9e26.png)

所以能不能给出一个这样的版本呢，加入headsep=0.3cm解决开始间距的问题，但一级标题不能上浮（不是指那一页都不上浮，而是带一级标题的那一页除一级标题外上浮）。

感谢大佬的辛苦工作，我只是（也只能）提出这个需求，有不对不科学的地方还请谅解。

**Comment by carryyu** [comment]
![目录](https://user-images.githubusercontent.com/26600630/170505716-a0b32393-2f7b-438b-99d6-66ce6b2b8929.png)
别的大多对齐差不多了，就是中文目录标题还是肉眼可见的，如果能下移一些就好了，请问这个可以在哪里调整吗，谢谢~

**Comment by obster-y** [comment]
看上一次 commit 的 diff 就知道我改了哪里
