### ISSUE TITLE
【dev分支】英文摘要段落间空行不明显，word模版要求英文摘要换段空一行

### ISSUE THREAD

**Issue by Wastoon** [obster-y/XJTU-thesis#72]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「MacOS」
 - TeX 发行版：「TeXLive」
 - 模板版本：「dev分支最新 / ...」
 - TeX 编辑器：「TeXShop」
 - TeX 编译方式：「xelatex+biber」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
word模版要求：
<img width="565" alt="image" src="https://user-images.githubusercontent.com/31173581/170612872-013e5351-90ba-4808-9729-0865fb0a0838.png">

【dev】换段未空行英文摘要：
<img width="929" alt="image" src="https://user-images.githubusercontent.com/31173581/170612570-9507e521-f849-44c5-8e28-33cdbefeedf5.png">

【master】换段空行摘要
<img width="525" alt="image" src="https://user-images.githubusercontent.com/31173581/170612682-950c7900-5840-4b9e-a9b1-0aff8b619941.png">

请问下，上述两种情况，哪一种是对齐了word最新版的模版的呢？还需要我们在英文摘要那边换段空行吗？

**Comment by carryyu** [comment]
dev分支自己在英文摘要里手动空行可以解决这个问题，比如每段结束后输入\\[8pt]

**Comment by Wastoon** [comment]
> 
非常感谢
