### ISSUE TITLE
摘要空行问题

### ISSUE THREAD

**Issue by wwwei1997** [obster-y/XJTU-thesis#73]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「TeXStudio 」
 - TeX 编译方式：「latexmk 」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
摘要最后与关键词的空行和关键词与论文类型的空行不等宽

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
![image](https://user-images.githubusercontent.com/52685230/170631619-eac0d53b-f1d9-4bf9-ae02-3b720cbb7ce8.png)

**其他说明**

**Comment by obster-y** [comment]
1. 没见到必需相等的要求，因此不在调整范围之内
2. 这里用了 parbox，不能用普通的段落方式定义
