### ISSUE TITLE
最新dev版本不生成bbl文件

### ISSUE THREAD

**Issue by jacky123465** [obster-y/XJTU-thesis#74]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [ ] 已搜索过历史 issue

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：Win 10
 - TeX 发行版：TeXLive 2021
 - 模板版本：dev分支最新 
 - TeX 编辑器：TeXStudio 
 - TeX 编译方式： xelatex+biber 

**Bug 说明（每项非必需填写，请尽量明了易懂）**
因马上要交图书馆，所以使用最新dev版本编译，发现生成不了bbl文件，参考文献无法显示。
已尝试clear.sh掉所有相关文件，依旧无法生成。

**Comment by obster-y** [comment]
什么都不提供，想回答也没有办法

**Comment by obster-y** [comment]
你至少提过三个 issue 了，还是不清楚怎么提问吗？

我有点懒得理你了都

**Comment by jacky123465** [comment]
> 什么都不提供，想回答也没有办法
您好。
问题如图所示，没有做任何修改，只是替换了Main_Spine、Main_Miscellaneous、References下面文件为自己的文件。所以没办法展示代码和错误截图。
之前也搜过相关问题。
![image](https://user-images.githubusercontent.com/22407341/170641820-84cd48d5-17c3-4efd-878a-f7710f12876a.png)

**Comment by obster-y** [comment]
我不想看你的论文内容，也不在乎你的论文内容

我在 bug 提问模板里说了，搜索历史 issue，你搜了吗？没有

如果你搜了，你就会发现有人提过相同的问题，并且有解决方案

我告诉你了怎么用（搜索历史issue），你不用，你不尊重我，我也可以没必要尊重你，但是我告诉你，这个问题之前出现过，并且我记得之前你的一个问题也是你自己不去搜索
