### ISSUE TITLE
关键词

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#75]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新 」
 - TeX 编辑器：「TeXStudio 」
 - TeX 编译方式：「latexmk」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
word版本关键词如果两行第二行会从头开始
![image](https://user-images.githubusercontent.com/55922272/170684986-2a18c669-26ee-4a2b-aefb-e73e24bae247.png)
latex则是冒号之后对齐
![image](https://user-images.githubusercontent.com/55922272/170685106-915eb93f-ddc3-49f0-80b1-ad0e5c78fef0.png)
想问下如何想改成word样式，应该如何更改

**Comment by obster-y** [comment]
https://github.com/obster-y/XJTU-thesis/issues/73#issuecomment-1139317274
