### ISSUE TITLE
使用情况反馈

### ISSUE THREAD

**Issue by JinglezZ** [obster-y/XJTU-thesis#8]
感谢作者和其余开发人员的花大量时间制作的模板，我用了三天多的时间把论文从旧的模板（2018年版）迁移到了新模板。我想站在 Latex 入门级用户的角度谈谈使用过程中的体会，或许能对模板的进一步提升有所帮助：）
### 模板样式方面

- 首先是引用部分。这几天迁移模板花的最多的时间在这两个方面：1.将 subfigure 语法修改为 subcaption 语法，这个没有问题， subfigure 太古老了是该抛弃。2. 将 cleveref 语法修改为简单的 ref 语法，这点我比较好奇，为什么在模板里面没有用更方便的 cleveref 宏包和语法，它能自动在引用前标注”图“、”表“、”公式“等，而且同时引用多个也会自动排列好，但是 ref 语法功能就比较简单，前面的标注需要一个一个自己手动加。所以如果不是存在宏包冲突等问题的话，是不是能考虑用 cleveref 宏包呢？
- 第二是跨页子图设置部分。word模板里面对跨页子图没有做特殊的标题规定，Latex模板里面采用 `\floatcontinue`  来连接跨页的子图，这种方式会使标题仅在第二页子图下方显示。不过我个人阅读文献的习惯，觉得第一页子图下方也标注标题，看起来会方便一点，因此我用`\ContinuedFloat`的方式来连接的跨页子图。这条纯属个人习惯，可以忽略。
- 第三是 TikZ 里面字体的设置，用 `font=\normalsize`、`font=\small`、`font=\footnotesize`不能实现字体依次变小的效果，只有当使用`font=\scriptsize`时字体一下子变得很小。不知道这个是不是因为模板里已经定义了前三个size的字号引起的，或者只是我使用不当。
### 编译方式及编译器使用方面

- 编译器部分，我使用的是 vscode。我是一个入门级使用者，在 vscode 里面配置 Latex 的编译方式都是按照网上的教程来的，比如经典的 xe->bib->xe-xe 编译方式。但是这个模板里面使用了 biber 编译方式，一下子就不太清楚该怎么修改 vscode 里面的设置实现编译，一直用的 `latexmk` 命令行方式编译。虽然可以完成编译过程，但是没有 vscode 语法的提示，找 bug 变得更难了。所以作者如果能在 readme 里面稍微提一下 vscode 里面怎么配置，我这样的入门级使用者就太感激了。
- 编译部分，首先是章节的插入，模板好像对章节名字还有顺序都有要求，虽然不如直接用 `\includeonly` 方便，但是这里应该有作者自己的考虑，而且算不得很麻烦。真正感觉到麻烦的是，单独编译其中一章的时候，不管是否注释了 `latexmkrc` 文件中的 `cleanup_mode`这一行，章节中的公式/图/表等编号以及参考文献的编号都会重新开始编，并且引用到被注释掉的章节的内容时会出现 `?` ，这种情况对于调整格式存在一些影响，为了提高编译速度通常会只编译需要修改的章节，注释掉其他章节，等调整好格式，全局编译后，却可能因为编号、引用变化的逐渐积累，使调整好的格式变乱。不知道这一点有没有好的解决办法。

以上是我在使用中遇到的一些问题和觉得能改进的地方，希望对模板的发展有所帮助。当然有些问题可能是我本人使用模板不当引起的，如果是的话提前说声抱歉。
最后再次感谢作者和其余开发人员的付出！

**Comment by obster-y** [comment]
收到您的回复，对调整模板很有用，会根据您的建议进一步修改

**Comment by obster-y** [comment]
对于样式方面的第一点，已经添加了 cleveref 并预设了大部分引用样式；第二点也增加了说明以供选择；第三点不是很明白具体的需求，也不认为在学位论文中应该实现自行调整字号。

对于编译方面，第一点已经在 README.md 中添加了部分 VS Code 的配置说明；第二点中，之前使用的正文章节的插入方式是因为试图要保持整体一致，同时正文章节与其他章节需要一些设置，所以添加了自定义的命令载入正文一次性解决，但还导致了自动跳转问题。

现在将其拆分为两组命令，可以使用 \include 与 \includeonly #3 ，同时在 README 增加了使用方法和注意事项。但是对于「却可能因为编号、引用变化的逐渐积累，使调整好的格式变乱」的问题，我不能认同，内容和格式分离，不能为了格式而去委曲内容，引用时也不会在乎具体的编号而是它具体的名字。

具体请参照 dev 分支的更新。

**Comment by JinglezZ** [comment]
> 对于样式方面的第一点，已经添加了 cleveref 并预设了大部分引用样式；第二点也增加了说明以供选择；第三点不是很明白具体的需求，也不认为在学位论文中应该实现自行调整字号。
> 
> 对于编译方面，第一点已经在 README.md 中添加了部分 VS Code 的配置说明；第二点中，之前使用的正文章节的插入方式是因为试图要保持整体一致，同时正文章节与其他章节需要一些设置，所以添加了自定义的命令载入正文一次性解决，但还导致了自动跳转问题。
> 
> 现在将其拆分为两组命令，可以使用 \include 与 \includeonly #3 ，同时在 README 增加了使用方法和注意事项。但是对于「却可能因为编号、引用变化的逐渐积累，使调整好的格式变乱」的问题，我不能认同，内容和格式分离，不能为了格式而去委曲内容，引用时也不会在乎具体的编号而是它具体的名字。
> 
> 具体请参照 dev 分支的更新。

谢谢您的修改！
关于 tikz 中的字号问题我详细说明一下。论文里面经常会用 tikz 画一些图，比如常见的流程图。论文模板中要求图的标题为五号字，图片内部的说明文字字号不得大于五号字，所以这里是需要自己调整字号的，下面是我做的一个例子：
```
\begin{figure}[ht!]
  \centering
  \begin{tikzpicture}
    \node (流程图 1) [font=\normalsize, rectangle, text centered, draw=black]  {流程图 1};
    \node (流程图 2) [font=\small,rectangle, text centered, draw=black, below = 0.5cm of 流程图 1]  {流程图 2};
    \node (流程图 3) [font=\footnotesize,rectangle, text centered, draw=black, below = 0.5cm of 流程图 2]  {流程图 3};
    \node (流程图 4) [font=\scriptsize,rectangle, text centered, draw=black, below = 0.5cm of 流程图 3]  {流程图 4};
  \end{tikzpicture}
  \vspace{0.5em}
  \caption{流程图}
\end{figure}
```
编译效果如下：
![image](https://user-images.githubusercontent.com/59874268/142197457-8302802a-fed7-40b9-bad0-6bf2e32b0e62.png)

在这个 `tikzpicture` 里面我设置了四种大小的字号，其中 `font=\normalsize` 的字号和正文一致；`font=\small` 与 `font=\footnotesize` 出来的字体大小一样，且看起来比标题字体稍微大一点，应该是略微大于五号字；而 `font=\scriptsize`又会突然变得很小，这就导致用 tikz 画的图字号不方便调整。

**Comment by sikouhjw** [comment]
https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/XJTU-thesis.cls#L605-L606
也许是 bug 吧

**Comment by JinglezZ** [comment]
> https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/XJTU-thesis.cls#L605-L606
> 
> 
> 也许是 bug 吧

啊，对不起！
我刚才用 ps 平移了一下标题文字，和 `\font=\small` 与 `\font=footnotesize` 设置下的文字其实是一样大小的，所以这两个 `\renewcommand` 是起作用了的。看起来流程图里面的字稍微大了一点点可能是外面加了方框后的视觉错误。
那这个问题可以完结了，谢谢作者！

**Comment by sikouhjw** [comment]
> 
> 
> > https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/XJTU-thesis.cls#L605-L606
> > 
> > 也许是 bug 吧
> 
> 啊，对不起！ 我刚才用 ps 平移了一下标题文字，和 `\font=\small` 与 `\font=footnotesize` 设置下的文字其实是一样大小的，所以这两个 `\renewcommand` 是起作用了的。看起来流程图里面的字稍微大了一点点可能是外面加了方框后的视觉错误。 那这个问题可以完结了，谢谢作者！

`\footnotesize` 和 `\small` 只有行距才有区别

**Comment by JinglezZ** [comment]
> > > https://github.com/obster-y/XJTU-thesis/blob/b28a5af5bd6b655e263a5831a12c7a0ebf2a862e/XJTU-thesis.cls#L605-L606
> > > 
> > > 也许是 bug 吧
> > 
> > 
> > 啊，对不起！ 我刚才用 ps 平移了一下标题文字，和 `\font=\small` 与 `\font=footnotesize` 设置下的文字其实是一样大小的，所以这两个 `\renewcommand` 是起作用了的。看起来流程图里面的字稍微大了一点点可能是外面加了方框后的视觉错误。 那这个问题可以完结了，谢谢作者！
> 
> `\footnotesize` 和 `\small` 只有行距才有区别

嗯嗯是的，我之前没去找这两行，只要看到这两行就不会有疑惑了
