### ISSUE TITLE
无法编译参考文献的问题

### ISSUE THREAD

**Issue by ScarletBlaze** [obster-y/XJTU-thesis#82]
目前电脑环境win10+texlive2022。使用学校研究生院模板http://gs.xjtu.edu.cn/info/1209/7605.htm或者本git下dev分支均出现了无法编译参考文献的问题，具体来说，正文中引用参考文献的地方，会如下。
![参考文献正文](https://user-images.githubusercontent.com/17705192/186367153-9eb647c0-3aea-4db2-8d85-33ef53d50109.png)
以及文章尾部未出现参考文献页

若学校模板使用texstudio时下方的消息会提示：
“!TeX 指定使用的程序无法识别！（latexmk）。回退为使用默认程序。”，如下图
![消息栏提示](https://user-images.githubusercontent.com/17705192/186365626-6e988fea-43ed-4726-841d-a9ea0b2bfd99.png)
若使用该git下的dev模板，会直接提示因为不是xeltex而终止，如下
![dev](https://user-images.githubusercontent.com/17705192/186367565-7ed176dd-188d-48c4-9700-1d52b5d684dc.png)

自己感觉是因为texstudio无法自动识别latexmk程序？
然后参考其它issues时改为手动使用 latexmk -xelatex main.tex 进行编辑dev分支时，仍旧会出现无参考文献的问题

谢谢了！

**Comment by sikouhjw** [comment]
1. 如何在 texstudio 中使用 latexmk 是另一个问题；
2. 手动使用 `latexmk -xelatex main.tex` 报什么错？

**Comment by ScarletBlaze** [comment]
> 1. 如何在 texstudio 中使用 latexmk 是另一个问题；
> 2. 手动使用 `latexmk -xelatex main.tex` 报什么错？

谢谢！
刚刚我又使用clear.bat清除文件后，重新下使用 `latexmk -xelatex main.tex` 命令后，截了可能存在报错信息的部分图，感觉好像是biber error，请问这种情况该怎么处理呢？

**Comment by obster-y** [comment]
有可能你的 .bib 文件格式有误，同时，这些日志可以直接上传一个 .log 文件。

如果想自行解决，建议检查一下 .bib 文件格式，或者作为附件发上来。

请使用 dev 分支而非学位办网上挂的模板

**Comment by ScarletBlaze** [comment]
> 有可能你的 .bib 文件格式有误，同时，这些日志可以直接上传一个 .log 文件。
> 
> 如果想自行解决，建议检查一下 .bib 文件格式，或者作为附件发上来

非常感谢！刚刚删除了bib中大部分条目后发现正常了。可能是之前存放的条目存在一些问题。请问有没有什么方法可以检查.bib文件中的每一项引用条目是否格式正常呢？

**Comment by obster-y** [comment]
https://tex.stackexchange.com/questions/173621/how-to-validate-check-a-biblatex-bib-file
