### ISSUE TITLE
[BUG] README 中的论文规范链接失效

### ISSUE THREAD

**Issue by yi-Xu-0100** [obster-y/XJTU-thesis#84]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「1.2.7(master分支) / dev分支最新」
 - TeX 编辑器：「VS Code」
 - TeX 编译方式：「latexmk」

**Bug 说明（每项非必需填写，请尽量明了易懂）**

README 中基本信息的 [学校的硕博学位论文要求](http://www.lib.xjtu.edu.cn/info/1102/1217.htm) 的指向链接已失效。

**最小代码示例**

https://github.com/obster-y/XJTU-thesis/blob/d80e4bb7d9f2b7f0b94d528bd38e46f01e1da44a/README.md?plain=1#L22-L24

**错误截图**

**其他说明**

我在图书馆中找到的最新关于论文的通知是：http://www.lib.xjtu.edu.cn/engine2/general/6897818/detail?engineInstanceId=361785&typeId=2493362&pageId=34094&websiteId=27676&currentBranch=0

其中提到了 `2021年最新学位论文模板及规范说明参考以下网页说明` 的最新网址<http://web.lib.xjtu.edu.cn/info/1102/1217.htm>，除了域名与 README 版本不一致，后续与 README 版本一致，所以可能是图书馆系统更新所导致的链接重定向错误。

我们可以看出这个参考链接对应给出的模板是 [2021XJTU-Thesis-LaTeX-修复20210328.zip](http://gs.xjtu.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1510757228&wbfileid=4583522) ，而且我下载不成功，所以此处暂且不管，应默认以[研究生院的模板](http://gs.xjtu.edu.cn/info/1209/7605.htm)为准。
但是可以发现，这里也仅给出对应的模板，而并没有给出对应的指导性说明规范。

最后，我在研究生院能够找到的最新规范要求为： http://gs.xjtu.edu.cn/info/1209/5614.htm

该处给出的规范是 2018 年的，即提供模板的网页提及的上一个被替换版本，至此，我们能够获得的**只有最新的模板文件**。

**Comment by obster-y** [comment]
1. 你说的还是不够清楚，但我大概看明白了
2. README 里图书馆的链接失效了，之后会换上新的，但是重点在于「 http://web.lib.xjtu.edu.cn/info/1102/1217.htm 」中提到了图书馆以研究生院的标准为准，所以下面的讨论不考虑图书馆的链接/文件了
3. 研究生院的链接「 http://gs.xjtu.edu.cn/info/1209/7605.htm 」没有改变，只是其中的附件内容有所变化
4. 如果你想要具体的规范，请查看研究生院链接中word类型附件，里面有具体的要求

**Comment by yi-Xu-0100** [comment]
@obster-y 非常感谢回复！

如果规范还是需要查看 word 类型模板的话，或许得考虑至少将其中的文字规范要求说明给整理出来，方便直接在该仓库作为参考。或者放到 https://github.com/obster-y/XJTU-thesis-Office 中，这边给出链接作为指引。
