### ISSUE TITLE
[BUG] 关于参考文献人名的讨论补充

### ISSUE THREAD

**Issue by yi-Xu-0100** [obster-y/XJTU-thesis#85]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「1.2.7(master分支) / dev分支最新」
 - TeX 编辑器：「VS Code」
 - TeX 编译方式：「latexmk」

**Bug 说明（每项非必需填写，请尽量明了易懂）**

Latex 版本中，参考文献部分已经指出，默认以 `gbt7714-2015` 的国标版本作为默认参考文献格式。但是同样指出官方的 word 模板中，学校的要求与国标版本有出入。我查看了 word 模板的内容，发现 word 模板的叙述如下：

<details>
<summary>展开查看 word 模板关于参考文献的部分说明引用</summary>
<blockquote>
<p>参考文献的著录格式应符合国家标准GB/T 7714-2015《文后参考文献著录规则》。参考文献中每条项目应齐全。</p>
<p>1. 顺序编码制</p>
<p>文献中的作者不超过三位时全部列出，超过三位时，一般<strong>只列前三位</strong>，中文的后面加 “<strong>，等</strong>”字，英文的后面加 “<strong>, et al</strong>”，作者姓名之间用<strong>逗号</strong>分开。</p>
<p>外国人名一般采用<strong>姓在前，名在后</strong>的著录法，<strong>姓全写且第一个字母大写，名简写成单个大写字母且不加标点</strong>，姓和名之间空1格，如：“Metcalf S W”。也可采用名在前，姓在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，名和姓之间空1格，如：“S W Metcalf”。</p>
中文人名的英文表达方式：</p>
<p>简写时，采用<strong>姓在前，名在后</strong>的著录法，<strong>姓全写且第一个字母大写，名简写成单个大写字母且不加标点</strong>，如，“钱学森”，简写为“Qian XS”。</p>
<p>全拼时，<strong>名在前，姓在后</strong>的著录法，名的第一个字母大写，名连写，名后空1格写姓，姓的第一个字母大写。如，“钱学森”，写为“Xuesen Qian”。</p>
<p>文后参考文献著录格式<strong>范例样板</strong>，采用五号。</p>
</blockquote>
</details>

**可以看出 word 模板提及符合国家标准在前，补充人名规范在后，有对特殊情况（与标准不同的地方）的补充说明的可能（此处为个人猜测）。**

是否应该在 **README 和使用手册**中给出 Latex 模板与 word 模板此部分的差异，并给出对应解决方案的链接（<https://github.com/obster-y/XJTU-thesis/issues/6#issuecomment-971636245>）?

**其他说明**

关于为何会有此差异的猜测：我发现在[ 2018 年研究生院的论文规范](http://gs.xjtu.edu.cn/info/1209/5614.htm)中，同样提及了国标和补充的人名规范，所以我第一时间是怀疑是否国标此处有模糊说明。

我从网上查找了[GB/T 7714-2015《文后参考文献著录规则》](http://journal.ustc.edu.cn/uploadfile/yjsjy/20161108/GB%20T%207714-2015%E4%BF%A1%E6%81%AF%E4%B8%8E%E6%96%87%E7%8C%AE-%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E8%91%97%E5%BD%95%E8%A7%84%E5%88%99.pdf)，发现在文件的前言中也仅找到与中文人名相关的修改说法，并没有提及整体大小写的问题。

<details>
<summary>展开查看GB/T 7714-2015《文后参考文献著录规则》 中前言部分关于人名的修正说明</summary>
<blockquote>
<p>在著录规则方面，将“8.1.1”中的“用汉语拼音书写的中国著者姓名不得缩写”改为“依据GB/T28039一2011有关规定，用汉语拼音书写的人名，姓全大写，其名可缩写，取每个汉字拼音的首字母”。在“8.8.2”中增加了“阅读型参考文献的页码著录文章的起讫页或起始页，引文参考文献的页码著录引用信息所在页”。在“8.5页码”中增补了“引自序言或扉页题词的页码，可按实际情况著录”的条款。新增了“8.6获取和访问路径”和“8.7数字对象统一标识符”的著录规则；</p>
</blockquote>
</details>

而在标准的 6.3 部分则指出了这个大小写的问题。

> 6.3 个人著者，其姓全部著录，字母全大写名可缩写为首字母（见8.1.1），如用首字无法识别该人名时，则用全名。

从 8.1.1 的示例也可以看出国标开始要求责任人名称全大写。

我尝试查找了被 GB/T 7714-2015 替换的 [GB/T 7714-2005 《文后参考文献著录规则》](http://jsuese.ijournals.cn/UploadFile/GBT%207714-2005%20%E6%96%87%E5%90%8E%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E8%91%97%E5%BD%95%E8%A7%84%E5%88%99.pdf)，发现在 2005 年标准中，6.3 没有提及字母全大写的问题。

> 6.3 个人著者，其姓全部著录，而名可以缩写为首字母(见 8.1.1);如用首字母无法识别该人名时，则用全名。

但是在 8.1.1 中的示例部分已经体现出字母全大写的状况。

我又往前追溯了[GBT 7714-1987 文后参考文献著录规则](https://www.wdfxw.net/doc95726847.htm),在6.1.1发现了人名字母小写的示例。

此时可以判断，在1987年的标准中，人名是小写示例，但没有文字说明。而在2005年的标准中，虽然将示例改为大写，但是没有文字说明。而在最新2015年的标准中，发现了6.3对于字母全大写的说明。

但可能考虑到往年的论文审查的问题，见参考 issue：

- #6 
- #9
- #63
- #77

所以还是希望给出对应的说明或者给出对应的指引链接。

### 总结

0. 该 issue 仅作为参考文献人名问题的溯源讨论，能够指出可能的历史遗留问题。
1. 希望**在 README 和使用说明**中给出指引链接和解决方案链接。
2. 在使用说明中，给出此部分差异的说明。

**Comment by obster-y** [comment]
1. 谢谢你的补充，包括溯源问题之前是没有提过的，感谢相关的信息
2. 关于在 README 中补充的问题，我实际上已补充过
https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md?plain=1#L288
3. 使用说明中，我没有显式的提及，但是我认为完成一篇硕士学位论文，至少也应该会在 issue 里搜索相关的问题及其解答，同时我也说明了提问须知

**Comment by obster-y** [comment]
最终的原因还是学校的模板有问题，自相矛盾，所以如果能够解决这一根本问题，这一Issue讨论的问题也不存在了

另外建议这类相关的问题可以去讨论区 Discussion 发表

**Comment by yi-Xu-0100** [comment]
@obster-y 

### 目前的情况

考虑到学校的沟通情况，**暂时**来说很难直接得出是否有一劳永益的解决方案。

但是关于参考文献人名的要求来说， README 和 使用说明中没有提及，而你所指出的 README 的补充（<https://github.com/obster-y/XJTU-thesis/blob/dev/LaTeX_Template/README.md?plain=1#L288>），也只是可能碰到的数字角标问题。

### 如何发现的这个问题

我想大部分人第一反应是直接启用模板，当然更近一步是能够找到 dev 并尝试最新版本，但是对于已经关闭的 issue，应该不是第一时间去关注的。

> 参考文献风格依照国标（不是学校的 Word 模板是因为其部分内容不符合国标，而它又要求国标）设置为「顺序编码制」。

而我是看到了 README 中这一句，让我好奇 word 模板中哪些部分要求与国标冲突？然后发现 word 模板的参考文献的关于人名的详细说法。为了弄明白是否是模板的问题，我尝试找了下模板以外的规范要求文件，又引起了 #84 的问题，最后发现没有找到对应的规范文件，只有模板文件。（当然以现在的说法，word 中的模板中的要求是规范。）

但是至此可以看出，我在 README 中隐性提及的问题后，还需要去查看或者翻找很多的文档和说明，而无法明确可能的问题。如果能显示引导出与国标不符合的但是是又有具体要求的部分，是否能够避免还需要在审查之后，再去寻求求助。

### 为何这个问题应该在 issue 而不是 Discussion

首先 issue 的优先级是高于 Discussion的，我会看下没解决的 issue ，而不去翻看 Discussion，因为我认为 issue 是潜在的 bug 反馈区，而 Discussion 则是未来的更近一步的说明文档的优化或者使用说明不清楚的讨论。

而该问题我看到了多次被提及，然后有给出解决方案，但是这**无法在第一次使用第一次模板时被轻易察觉**（使用模板，不会去关注 README，可能只是看下使用手册了），甚至可能会在各种审核返回后才被发现，继而需要考察是否模板有误。这对于毕业论本模板这个**仅使用一次到两次的工具**来说，很难在第一时间明确了解到这个问题，而是被动的根据审核反馈才会去了解到这个问题显然是不太合适的。

所以这个 word 模板被提及的参考文献人名问题，即使在 Latex 不是**显式支持**的，那在 README 和使用说明中给出对应的引导也是十分有必要的。

**Comment by obster-y** [comment]
1. 对于已经关闭的 issue，我在提问须知里，说明了要查看，如果不看，那我可以认为这样的使用者不在我的服务范围内
2. 还需要去查看或者翻找很多的文档和说明，这似乎是应该的，使用工具前认真查看工具说明是基本要求。因为按照默认情况来说，参考文献是按照国标输出的，而做格式审查的人是不按照国标审查的，所以本来就没有问题，自然不存在提示的问题，更需要的是改变规则，不要让审查的人按照错误的标准进行工作
3. 为何应该在 Discussion 而不是 issue，因为我不觉得谁的优先级比较高，而是有不同的功能属性。同时这也不是模板的「Bug」，而是你自己说的「说明文档的优化」，或者「使用说明不清楚的情况」
4. 一个问题多次被提及，除了本身反映的问题，是因为提问的人不会搜索。我没有义务教别人怎么搜，同时我在提问说明说的很清楚，自己不看历史问题反复重复提问，很难说是我的错
5. 对于一份文档，审核后再改是很有必要的。我不清楚审核的是什么人，有什么要求，我不会在事前在乎，我只在乎这个东西是不是按照规则做出来的，如果规则有问题，那就改规则。我没有心情做一个事前准备好应对所有需求的完美产品。所以，根据审核反馈才了解这个问题是非常合适的，很多时候审核的人不懂，在那里层层加码，为了防止他们手上出问题，但那和我没有任何关系，我不会惯着他们
6. 我不明白「显式支持」是什么意思
7. 感谢你的建议，但是很明显这些建议，还是建议挪到 Discussion，同时如果你愿意，并且有能力，可以自己修改 README 然后提交 PR，我很乐意合并或作出修改
