### ISSUE TITLE
[BUG]某些汉字显示不正常【例如：璟】

### ISSUE THREAD

**Issue by zyylvs** [obster-y/XJTU-thesis#86]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Overleaf」
 - TeX 发行版：「TeXLive 2022」
 - 模板版本：「 dev分支最新」
 - TeX 编辑器：「Overleaf」
 - TeX 编译方式：「xelatex+biber」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
某些汉字显示不正常，例如：璟。实际显示是个F字母，加一个框。

**最小代码示例**
以下代码可以正常显示【璟】，但是不知道这个模板如何修改字体族。
\documentclass[fontset=ubuntu]{ctexart}
\usepackage{ctex}
% 导言区
\usepackage{enumitem}
\begin{document}
景璟
\end{document}

**错误截图**
璟字的错误截图。
<img width="72" alt="image" src="https://user-images.githubusercontent.com/24310311/195138266-ee0306f2-eeea-4485-97c2-2d90ba0c5716.png">

**其他说明**
无

**Comment by sikouhjw** [comment]
fandol 缺字，
https://github.com/obster-y/XJTU-thesis/blob/11bf5fbeba86b428c89f9d3a525030d8cdf06bb8/LaTeX_Template/XJTU-thesis.cls#L276-L287
可以参考
https://github.com/sikouhjw/gdutthesis/blob/a5f3d8110bf011773cdd91bada27d81620219b53/gdutthesis.cls#L797-L828
来配置 Overleaf 上的字体

**Comment by zyylvs** [comment]
@sikouhjw 这个配置看不太懂。。。
我后来的做法是：
按照现有代码的提示，把字体文件simhei.ttf、simsun.ttc上传到XJTU-thesis.cls的同级目录。
把281到283，修改为
   \setCJKmainfont[AutoFakeBold=true]{simsun.ttc} 
   \newfontfamily{\heiti@letter}{simhei.ttf} 
   \newfontfamily{\songti@letter}{simsun.ttc} 
可以正常编译，也可以正常显示璟字。就是第一次全量编译，需要10分钟。

那这个问题不算bug了，等一两天之后，我把这个issue 关闭。
