### ISSUE TITLE
参考文献 中文人名的英文表达方式 问题咨询

### ISSUE THREAD

**Issue by Gausx** [obster-y/XJTU-thesis#9]
安装学校官方给的word模板里边 关于：中文人名的英文表达方式
提出两种方式：
简写时，采用姓在前，名在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，如，“钱学森”，简写为“Qian XS”。
全拼时，名在前，姓在后的著录法，名的第一个字母大写，名连写，名后空1格写姓，姓的第一个字母大写。如，“钱学森”，写为“Xuesen Qian”。
我们模板里边采用的第一种方式，但是里边有两个问题。
第一个，姓氏只应该首字母大写，我们模板目前全部是大写，外国人的英文名也是如此。
第二个，例如“钱学森”，简写为“Qian XS”，模板中会变成QIAN X，最后边的S丢掉了，我尝试将参考文献中的名字更改为Qian Xuesen 、Qian XueSen 均不起作用 ，这两个问题请问我应该如何更正？

**Comment by sikouhjw** [comment]
https://github.com/obster-y/XJTU-thesis/issues/6

**Comment by Gausx** [comment]
> #6

第二个问题，国标也是QIAN X就可以吗

**Comment by sikouhjw** [comment]
> 
> 
> > #6
> 
> 第二个问题，国标也是QIAN X就可以吗

```tex
\begin{filecontents*}{test.bib}
@book{fan2013food,
  author       = {Fan, Xue tong and Sommers, Christopher H.},
  title        = {Food Irradiation Research and Technology},
  edition      = {2},
  address      = {Ames, Iowa},
  publisher    = {Blackwell Publishing},
  year         = {2013},
  pages        = {25--26},
  urldate      = {2014-06-26},
  url          = {http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary},
}
\end{filecontents*}
\documentclass{article}
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
\begin{document}
  test\cite{fan2013food}
  \bibliography{test}
\end{document}
```

**Comment by Gausx** [comment]
> > > #6
> > 
> > 
> > 第二个问题，国标也是QIAN X就可以吗
> 
> ```
> \begin{filecontents*}{test.bib}
> @book{fan2013food,
>   author       = {Fan, Xue tong and Sommers, Christopher H.},
>   title        = {Food Irradiation Research and Technology},
>   edition      = {2},
>   address      = {Ames, Iowa},
>   publisher    = {Blackwell Publishing},
>   year         = {2013},
>   pages        = {25--26},
>   urldate      = {2014-06-26},
>   url          = {http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary},
> }
> \end{filecontents*}
> \documentclass{article}
> \usepackage{gbt7714}
> \bibliographystyle{gbt7714-numerical}
> \begin{document}
>   test\cite{fan2013food}
>   \bibliography{test}
> \end{document}
> ```

这样Fan X T 和word里边的规定的Fan XT 又冲突了 不过我看了国标他规定的应该是Fan X T

**Comment by sikouhjw** [comment]
> 
> 
> > > > #6
> > > 
> > > 
> > > 第二个问题，国标也是QIAN X就可以吗
> > 
> > 
> > ```
> > \begin{filecontents*}{test.bib}
> > @book{fan2013food,
> >   author       = {Fan, Xue tong and Sommers, Christopher H.},
> >   title        = {Food Irradiation Research and Technology},
> >   edition      = {2},
> >   address      = {Ames, Iowa},
> >   publisher    = {Blackwell Publishing},
> >   year         = {2013},
> >   pages        = {25--26},
> >   urldate      = {2014-06-26},
> >   url          = {http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary},
> > }
> > \end{filecontents*}
> > \documentclass{article}
> > \usepackage{gbt7714}
> > \bibliographystyle{gbt7714-numerical}
> > \begin{document}
> >   test\cite{fan2013food}
> >   \bibliography{test}
> > \end{document}
> > ```
> 
> 这样Fan X T 和word里边的规定的Fan XT 又冲突了 不过我看了国标他规定的应该是Fan X T

#6

**Comment by Gausx** [comment]
> > > > > #6
> > > > 
> > > > 
> > > > 第二个问题，国标也是QIAN X就可以吗
> > > 
> > > 
> > > ```
> > > \begin{filecontents*}{test.bib}
> > > @book{fan2013food,
> > >   author       = {Fan, Xue tong and Sommers, Christopher H.},
> > >   title        = {Food Irradiation Research and Technology},
> > >   edition      = {2},
> > >   address      = {Ames, Iowa},
> > >   publisher    = {Blackwell Publishing},
> > >   year         = {2013},
> > >   pages        = {25--26},
> > >   urldate      = {2014-06-26},
> > >   url          = {http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary},
> > > }
> > > \end{filecontents*}
> > > \documentclass{article}
> > > \usepackage{gbt7714}
> > > \bibliographystyle{gbt7714-numerical}
> > > \begin{document}
> > >   test\cite{fan2013food}
> > >   \bibliography{test}
> > > \end{document}
> > > ```
> > 
> > 
> > 这样Fan X T 和word里边的规定的Fan XT 又冲突了 不过我看了国标他规定的应该是Fan X T
> 
> #6

非常感谢回答
