### ISSUE TITLE
[BUG] 主要符号表没有显现

### ISSUE THREAD

**Issue by GorgeShao** [obster-y/XJTU-thesis#90]
Latex模板大佬，

您好！

**必要任务** 
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「dev分支最新」
 - TeX 编辑器：「Overleaf」
 - TeX 编译方式：「xelatex」

**Bug 说明**
主要符号表没有显现
可以编译成功生成pdf

**最小代码示例**
未更改dev中的代码

**Comment by sikouhjw** [comment]
这不是 bug。
```
xelatex main.tex
makeglossaries main
xelatex main.tex 
```

**Comment by obster-y** [comment]
建议读使用手册😅
https://github.com/obster-y/XJTU-thesis/blob/11bf5fbeba86b428c89f9d3a525030d8cdf06bb8/LaTeX_Template/README.md?plain=1#L147-L160

**Comment by obster-y** [comment]
另外 不清楚你是否看了这一个 毕竟是放在 issue 区最上面的
https://github.com/obster-y/XJTU-thesis/issues/35#issue-1171804831

**Comment by GorgeShao** [comment]
大佬，我是个Tex新人，使用Win10 + Texlive2022 + texstudio，我将编译设置为XeLaTex + Biber。

我根据大佬的提示，我现在的编译方式是：
1）在命令行里输入xelatex main.tex; makeglossaries main; xelatex main.tex，实现第一步编译；
2）然后在texstudio里使用F5构建并编译。之后论文pdf会自动在adobe的外部查看器里打开。

并出现以下编译信息(目前是可以成功编译出pdf的)：
Latexmk: Missing input file 'main.toc' (or dependence on it) from following: 'No file main.toc.'
Latexmk: Missing input file 'main.toe' (or dependence on it) from following: 'No file main.toe.'
Latexmk: Missing input file 'main.gls' (or dependence on it) from following: 'No file main.gls.'
Warning: File 'main.slo' is empty. Have you used any entries defined in glossary 'symbols'?”

我想问：
这些编译信息是不是因为我少什么东西？
这样编译是不是太麻烦了，每次改动后，都需要开命令行，有没有什么简便方式？
还有请问在Texstudio里可以输出命令行吗，就是不切换成Win10 的 cmd，按一个F5直接搞定？

还请大佬指教！

问候！

**Comment by obster-y** [comment]
texstudio 可以设置编译方式为 latexmk, 模板自带的 latexmkrc 集成了所有的编译步骤, 让 texstudio 自动识别 latexmkrc, 这样不需要命令行

同时并不建议每一次都全量编译，通常情况下只 xelatex 看看主要内容即可，全量编译相对比较费时

你还可以选择不用 f5 编译, 直接在命令行输入 latexmk 编译
