### ISSUE TITLE
答辩委员会页【答辩人：】、【答辩委员会委员：】、【答辩时间】和【答辩地点】应有【3字符】的缩进

### ISSUE THREAD

**Issue by KangWang146503** [obster-y/XJTU-thesis#91]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x ] 已搜索过历史 issue
- [ x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10」
 - TeX 发行版：「TeXLive 2022」
 - 模板版本：「 dev分支最新」
 - TeX 编辑器：「overleaf」
 - TeX 编译方式：「xelatex」

研究生院官网发布的word模板中 答辩委员会页【答辩人：】、【答辩委员会委员：】、【答辩时间】和【答辩地点】条目有【3字符】的缩进，而latex模板中没有缩进。

【latex效果如下】
![image](https://user-images.githubusercontent.com/82068510/217416434-3d5b9ef6-cf3c-422a-a048-b59eebe23c5c.png)
【word模板】
![image](https://user-images.githubusercontent.com/82068510/217416744-d2051b05-f49a-4a09-9859-6821a794b912.png)
![image](https://user-images.githubusercontent.com/82068510/217416156-64b48b85-d909-4890-a205-5ad5dbcc0579.png)

**Comment by sikouhjw** [comment]
https://github.com/obster-y/XJTU-thesis/blob/d80e4bb7d9f2b7f0b94d528bd38e46f01e1da44a/XJTU-thesis.cls#L992-L998
在这里加三个全角空格『　』。其实没必要纠结。

**Comment by KangWang146503** [comment]
好的，谢谢您

**Comment by KangWang146503** [comment]
加入三个全角空格后，委员姓名栏也缩进了三个字符，而word模板中这部分并没有缩进
![image](https://user-images.githubusercontent.com/82068510/217697841-cfac9ca0-a9a3-4e9e-8478-1d5dc9df0022.png)
感谢大佬们的辛勤劳动(^v^)

**Comment by sikouhjw** [comment]
模板的處理邏輯和 word 不同，改這地方毫無意義。如果沒能力改就不要改了，除非你重寫這一部分。

**Comment by KangWang146503** [comment]
好的 谢谢
