### ISSUE TITLE
[BUG] 请填写简短的 Bug 说明

### ISSUE THREAD

**Issue by Rainmes** [obster-y/XJTU-thesis#94]
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 」
 - TeX 发行版：「TeXLive 2021」
 - 模板版本：「1.2.7(master分支)」
 - TeX 编辑器：「TeXStudio 」
 - TeX 编译方式：「 xelatex+biber 」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
插入图的过程中超过一行的图名不居中

**最小代码示例**
\begin{figure}[H]
	\centering
	\includegraphics[width=0.6\textwidth]{粗糙度5.pdf}
	\caption{不同切削条件下不同朝向UD CFRP层的加工表面粗糙度（标签C1，C2，C3与C4含义在表\ref{切削工况}中给出）} \label{粗糙度5}
\end{figure}

**错误截图**
![image](https://user-images.githubusercontent.com/24714771/221332591-a5e84758-4d32-404a-81ad-ff2307a19b17.png)

**其他说明**

**Comment by sikouhjw** [comment]
模板的相关设置是
https://github.com/obster-y/XJTU-thesis/blob/d80e4bb7d9f2b7f0b94d528bd38e46f01e1da44a/XJTU-thesis.cls#L761
这仍然是居中的
```tex
\documentclass{article}
\usepackage{caption}
\captionsetup{format=hang}
\usepackage{lipsum}
\begin{document}
\begin{figure}
  \caption{\lipsum[1]}
\end{figure}
\end{document}
```

你想要的效果也许是
```tex
\documentclass{article}
\usepackage{caption}
\captionsetup{format=hang,justification=centering}
\usepackage{lipsum}
\begin{document}
\begin{figure}
  \caption{\lipsum[1]}
\end{figure}
\end{document}
```
问题在于，这只是多行时行为不同，不影响『整体居中』，所以请根据学校的规定来选择。

如果学校没有规定多行的行为，那就『都可以』，并且该模板是被学位办认可的，纠结于形式是没有意义的。

**Comment by Rainmes** [comment]
已解决  谢谢解答
