### ISSUE TITLE
[BUG] 未作任何修改，原始PDF中目录的页码已经不正确

### ISSUE THREAD

**Issue by Serenade600** [obster-y/XJTU-thesis#95]
**以下信息都不相关**。在原始PDF文件中，内容上33页是附录，目录中33页是研究成果。

------------
**必要任务** (请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史 issue
- [x] 已搜索过已经关闭的 issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：「Win 10 / Win 7 / MacOS / Linux发行版 / ...」
 - TeX 发行版：「TeXLive 2021 / MikTeX / CTeX / ...」
 - 模板版本：「1.2.7(master分支) / dev分支最新 / ...」
 - TeX 编辑器：「TeXStudio / WinEdt / VS Code / ...」
 - TeX 编译方式：「latexmk / xelatex+biber / pdflatex / ...」

**Bug 说明（每项非必需填写，请尽量明了易懂）**
为了实现 XX 功能/效果
使用了 XX 语句/命令
得到了 XX 结果

**最小代码示例**
如果可以，请在附录上传最小代码示例，以及日志 / 辅助文件

**错误截图**
非必要不要上传代码截图

**其他说明**

**Comment by obster-y** [comment]
1. 请不要自以为是，不然我没有必要回答
2. 如果不想按模板提问，可以去 Discussion 区
3. 请提供更详细的信息，比如说明什么叫「原始文件」

**Comment by Serenade600** [comment]
原始文件指未作修改的模板本身，也指从学校官网下载的模板文件。

对模板自信是好处。我尝试指出模板文件中的错误之处，如有不对请指出。

下面是正文第33页。
![image](https://user-images.githubusercontent.com/40297752/226336345-f69b22a9-dcc1-4eae-8452-cb2b4246e496.png)

下面是目录中
![image](https://user-images.githubusercontent.com/40297752/226338074-c68a65a7-b7bd-457e-b687-21ade38ff4f4.png)

**Comment by obster-y** [comment]
1. 学位办发布的模板是1.2.7版，我在本项目的介绍中说了请使用最新的 dev 分支，1.2.7可能有这个问题但它不在我目前的工作范围，同时我查看了新版本没有出现这个问题。
2. 我并非是对模板自信，而是因为你所说的“以下信息都不相关”，比如你没有说清楚你的问题是来自于哪个版本，没有按照我给出的模板填写内容，包括 pdf 至少也应该有个名字，是初始的 “使用说明.pdf” 还是编译生成的 "main.pdf"，如果是使用说明，为什么要在意使用说明呢，而不是在意编译出的文档？如果是编译出的文档，为什么不说清楚编译方式和平台软件版本呢？你都没有说清楚。这很明显是你自以为是，你认为你给出的信息已经足够，实际上并不够。

**Comment by Serenade600** [comment]
1. 新版本没有问题，这是你我都希望看到的结果。
2. 你评价我自以为是，但我请你注意，在某一版的readme.md中，其并未像现在强调“使用 dev 分支的最新发布内容”，而仅仅说明“dev分支保持基本内容同研究生院版本一致但开发新功能，请注意区分”。
3. 版本1.2.7的页码bug是“使用说明.pdf”和“main.pdf”都出现的问题。但这个问题显然不是“新功能”，我当然认为是模板自身的问题，我当然认为这个问题出现在所有版本里。我之前说“以下信息都不相关”是为了更快速的交流，你固执于填写issue模板我可以理解、甚至支持。但我要强调，站在我的角度我的做法是说得通的，你认为没有提供你要的信息就是自以为是恰恰是真正的自以为是。
4. readme.md被改写了。那我确实不知道这个项目还是这么维护的，这么重要的信息更改没有显著标明。我建议把使用最新dev分支的建议写在第一行最明显处。同时需要强调风险自负，因为用户未必会经常关注新版本。

**Comment by obster-y** [comment]
1. 这个项目是我在维护，是我在回答问题，提供对应的信息是因为我回答了几十个 issue，认为这样能帮助我快速查错，方便回答，不是为了你方便，如果不喜欢可以不用
2. 我并非固执于填写模板，而是在乎提供信息，信息够了，格式并不重要，但没有信息就不行。你所说的在两个文件里都出现的问题，在原始提问中并不存在。如果你到现在还认为你一开始的提问给予了充足的信息，那我觉得可以不用继续讨论了
3. 这个项目很奇怪的原因在于研究生院的模板不能及时更新，因此 readme 有变化
4. 你的建议很中肯，谢谢，并且我会之后更新中添加上这一点

**Comment by obster-y** [comment]
另外
1. 如果想要为了「更快速的交流」，应该去 Discussion 区，那里的问题我也会看，如果选择提 Issue，选了 Issue 模板，自然按照模板提示给予充足的信息是不错的选择，而不是「自认为」
2. 你认为「这个问题出现在所有版本里」是没有问题的，但是这个和提供你具体使用的是哪个版本有什么关系呢？你说你用的 A，我自然就看 A，我没有必要为了一条不够详细的问题把 ABC 版本都看一遍
3. 站在你的角度说得通不代表在我这就说得通，你已经间接承认了你的行为是基于你的判断的，因此我认为是「自以为是」似乎也没有错
4. 你认为我「没有提供我要的信息就是自以为是」，我的看法是，参考第一条，如果用了 Issue 模板，就建议按照模板来，哪怕你把模板内容清空了我也不会认为你是「自以为是」，恰恰是你保留了 Issue 模板内容，你认为 Issue 模板对你解决这个问题是冗余的，所以我会认为你是「自以为是」
5. 总的来说，我对你的**这件事**的评价是「自以为是」，我认为我没有错。同时，改编一句歌词「在我地盘这，建议最好还是听我的」
