### ISSUE TITLE
插入图片时，如果固定为top，则图题与正文间距变大

### ISSUE THREAD

**Issue by presto-wei** [obster-y/XJTU-thesis#96]
**必要任务**(请在 [ ] 内填入 "x" 表明完成此项任务
 - [x] 已搜索过历史issue
 - [x] 已搜索过已经关闭的issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：[Win 10]
 - TeX 发行版：[TeXLive 2023]
 - TeX 编辑器：[VS Code]
 - TeX 编译方式：[latexmk]
 - Word 版本：[2019]

**Bug 说明**
插入图片时，如果固定为top，则图题与正文间距变大

**最小代码示例**
\xchapter{测试}{TEST}
\zhlipsum[2]
\begin{figure}[H]
  \centering
  \includegraphics[width=13.5cm]{test.png}
  \caption[short]{测试}
\end{figure}
\zhlipsum[2,5]
\begin{figure}[t]
  \centering
  \includegraphics[width=13.5cm]{test.png}
  \caption[short]{测试}
\end{figure}

**错误截图**
非必要不要上传代码截图
![image](https://user-images.githubusercontent.com/27005213/227895313-169be687-9ea8-4241-bf6b-7ad1703b23ea.png)

**其他说明**

**Comment by sikouhjw** [comment]
不影响使用，建议别管。

想调可以参考 https://github.com/sikouhjw/gdutthesis/blob/19b068e9ef1685443204040206dace634b927228/gdutthesis.cls#L1127-L1153

**Comment by presto-wei** [comment]
嗯，明白了
