### ISSUE TITLE
直接下载dev分支代码，使用项目提供的配置文件在vscode编译报错

### ISSUE THREAD

**Issue by presto-wei** [obster-y/XJTU-thesis#98]
**必要任务**(请在 [ ] 内填入 "x" 表明完成此项任务
 - [x] 已搜索过历史issue
 - [x] 已搜索过已经关闭的issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：[Win 10]
 - TeX 发行版：[TeXLive 2023]
 - TeX 编辑器：[VS Code]
 - TeX 编译方式：[latexmk]
 - Word 版本：[2019]

**Bug 说明**
直接下载dev分支代码，在vscode本地编译，不显示参考文献和个人研究成果，代码未做任何更改，vscode配置文件为项目所提供配置

**最小代码示例**
vscode配置信息
![image](https://user-images.githubusercontent.com/27005213/229286072-0958bb72-182a-400d-866c-d5939e438a4f.png)

**错误截图**
报错信息
![image](https://user-images.githubusercontent.com/27005213/229286132-f0b9dea0-9b62-4e62-aed8-c984d6a9db7b.png)
![image](https://user-images.githubusercontent.com/27005213/229286141-8ca9888d-de3d-4fdd-9e99-9c9f914486fd.png)

**其他说明**
这是日志文件

[main.log](https://github.com/obster-y/XJTU-thesis/files/11129314/main.log)

**Comment by presto-wei** [comment]
直接使用latexmk main.tex
进行命令行手动编译，可以正常显示，但是存在一点问题，问题截图如下
![image](https://user-images.githubusercontent.com/27005213/229286746-809f3d50-b181-496d-9266-dfa0fadf62fb.png)
日志文件为：
[main.log](https://github.com/obster-y/XJTU-thesis/files/11129343/main.log)

**Comment by presto-wei** [comment]
把配置文件中的pdf选项注释掉，在vscode可以正常编译，但是没有显示参考文献和个人研究成果

**Comment by obster-y** [comment]
看起来是没有选到正确的 latexmkrc 文件，可以在工程里用 shell 手动调用一下 latexmk

**Comment by obster-y** [comment]
> 直接使用latexmk main.tex 进行命令行手动编译，可以正常显示，但是存在一点问题，问题截图如下 ![image](https://user-images.githubusercontent.com/27005213/229286746-809f3d50-b181-496d-9266-dfa0fadf62fb.png) 日志文件为： [main.log](https://github.com/obster-y/XJTU-thesis/files/11129343/main.log)

存在一点「什么」问题？还是没有参考文献和个人研究成果？日志看出来的内容不够多，感觉和bib文件不足有关系。而且我觉得这应该不是模板的问题，如果愿意的话可以提供一下 MWE，不然只能建议自己搜索解决了

**Comment by presto-wei** [comment]
这是清楚临时文件之后，重新在命令行调用latexmk main.tex，命令行输出的结果，显示退出代码12，命令错误
![image](https://user-images.githubusercontent.com/27005213/229294259-d4640917-29ce-4a08-9196-cc05b3cf70c2.png)
并且没有参考文献和个人研究成果，部分引用显示如下
![image](https://user-images.githubusercontent.com/27005213/229294288-c7305cde-b666-4077-ad66-7526f24c4819.png)

**Comment by sikouhjw** [comment]
1. 第一次提问，问题在于你用了 `latexmk -pdf`，这表示使用 `pdflatex`，而模板要求用 `xelatex`，看报错就知道了。
2. 第二次提问，问题大概在于 bib 的问题，可能是没有进行 biber，也可能是找不到 bib 文件

**Comment by presto-wei** [comment]
pdf选项的情况，我后续注释了，在vscode上可以编译，但是显示不了参考文献和个人研究成果

**Comment by presto-wei** [comment]
第二个问题，我也不清楚，抱歉

**Comment by sikouhjw** [comment]
建议用 Overleaf，可能是环境的问题

**Comment by presto-wei** [comment]
嗯，我正在用overleaf编译

**Comment by presto-wei** [comment]
overleaf可以，正常编译

**Comment by sikouhjw** [comment]
> 直接使用latexmk main.tex 进行命令行手动编译，可以正常显示，但是存在一点问题，问题截图如下 ![image](https://user-images.githubusercontent.com/27005213/229286746-809f3d50-b181-496d-9266-dfa0fadf62fb.png) 日志文件为： [main.log](https://github.com/obster-y/XJTU-thesis/files/11129343/main.log)

我在查看你提供的 log 文件时，发现一处警告在于
```
LaTeX Warning: Reference `fig:c4:cex_llvip' on page 1 undefined on input line 1
77.
```
而模板中是没有这个 `\cite`, `\ref` 或者 `\label` 的，所以我认为你编译的不是从 github 下载的

**Comment by presto-wei** [comment]
哦，这是我自己编译的自己的文件，

**Comment by presto-wei** [comment]
但是除了修改自己论文之外，其他的我没改，可能是我安装latex环境错误了，在overleaf上就完全没问题了

**Comment by sikouhjw** [comment]
> 但是除了修改自己论文之外，其他的我没改，可能是我安装latex环境错误了，在overleaf上就完全没问题了

所以这与你说的
> 直接下载dev分支代码

不符，而我们不知道你说的
> 除了修改自己论文之外，其他的我没改

到底改了什么，所以无从判断。目前只能认为是你的环境有问题。

**Comment by presto-wei** [comment]
嗯，麻烦大佬了，
