### ISSUE TITLE
golssary.tex文件为空，编译出的符号表文件出现大量逗号

### ISSUE THREAD

**Issue by presto-wei** [obster-y/XJTU-thesis#99]
必要任务(请在 [ ] 内填入 "x" 表明完成此项任务
- [x] 已搜索过历史issue
- [x]  已搜索过已经关闭的issues

**软件信息（请补全，只填写与模板类型相关的项，请务必填写准确）**
 - 操作系统：[Win 10 ]
 - TeX 发行版：[TeXLive 2023]
 - TeX 编辑器：[Overleaf]
 - TeX 编译方式：[xelatex+biber]
 - Word 版本：[2016 / 2019 ]

**Bug 说明**
我没有需要展示的符号，因此删除了glossary文件中所有内容，但是编译生成的符号表出现大量逗号

**最小代码示例**

**错误截图**
![image](https://user-images.githubusercontent.com/27005213/230563179-e21e0248-e41b-4ec5-9971-5a728d70b643.png)

**其他说明**

**Comment by obster-y** [comment]
自己回去看说明，不要什么都发 Issue，还用「Bug」的模板，去 Discussion 区

你知道什么叫做「Bug」吗？没有出现预期的结果不一定是「Bug」，有可能是你根本就没有正常操作，而这个结果是你不会用，或者不按照使用说明造成的

你不是第一次这样不按要求发 Issue 了，所以我不会直接回答你这个问题，你的问题的答案在README里自己去找

如果下一次还是这样，我会直接删除你的 Issue

**Comment by presto-wei** [comment]
抱歉，我的问题，实在对不起
